
# Never use "---" as it makes using these constants impossible

# Map IDs
MAP_EASTERNKINGDOM = 0
MAP_KALIMDOR = 1
MAP_OUTLAND = 530
MAP_NORTHREND = 571

# Game Object Types
GAMEOBJECT_TYPE_DOOR = 0
GAMEOBJECT_TYPE_BUTTON = 1
GAMEOBJECT_TYPE_QUESTGIVER = 2
GAMEOBJECT_TYPE_CHEST = 3
GAMEOBJECT_TYPE_BINDER = 4
GAMEOBJECT_TYPE_GENERIC = 5
GAMEOBJECT_TYPE_TRAP = 6
GAMEOBJECT_TYPE_CHAIR = 7
GAMEOBJECT_TYPE_SPELL_FOCUS = 8
GAMEOBJECT_TYPE_TEXT = 9
GAMEOBJECT_TYPE_GOOBER = 10
GAMEOBJECT_TYPE_TRANSPORT = 11
GAMEOBJECT_TYPE_AREADAMAGE = 12
GAMEOBJECT_TYPE_CAMERA = 13
GAMEOBJECT_TYPE_MAP_OBJECT = 14
GAMEOBJECT_TYPE_MO_TRANSPORT = 15
GAMEOBJECT_TYPE_DUEL_ARBITER = 16
GAMEOBJECT_TYPE_FISHINGNODE = 17
GAMEOBJECT_TYPE_RITUAL = 18
GAMEOBJECT_TYPE_MAILBOX = 19
GAMEOBJECT_TYPE_AUCTIONHOUSE = 20
GAMEOBJECT_TYPE_GUARDPOST = 21
GAMEOBJECT_TYPE_SPELLCASTER = 22
GAMEOBJECT_TYPE_MEETINGSTONE = 23
GAMEOBJECT_TYPE_FLAGSTAND = 24
GAMEOBJECT_TYPE_FISHINGHOLE = 25
GAMEOBJECT_TYPE_FLAGDROP = 26
GAMEOBJECT_TYPE_MINI_GAME = 27
GAMEOBJECT_TYPE_LOTTERY_KIOSK = 28
GAMEOBJECT_TYPE_CAPTURE_POINT = 29
GAMEOBJECT_TYPE_AURA_GENERATOR = 30
GAMEOBJECT_TYPE_DUNGEON_DIFFICULTY = 31
GAMEOBJECT_TYPE_BARBER_CHAIR = 32
GAMEOBJECT_TYPE_DESTRUCTIBLE_BUILDING = 33
GAMEOBJECT_TYPE_GUILD_BANK = 34
GAMEOBJECT_TYPE_TRAPDOOR = 35

# NPC Emotes
NPC_EMOTE_ONESHOT_NONE = 0
NPC_EMOTE_ONESHOT_TALK = 1
NPC_EMOTE_ONESHOT_BOW = 2
NPC_EMOTE_ONESHOT_WAVE = 3
NPC_EMOTE_ONESHOT_CHEER = 4
NPC_EMOTE_ONESHOT_EXCLAMATION = 5
NPC_EMOTE_ONESHOT_QUESTION = 6
NPC_EMOTE_ONESHOT_EAT = 7
NPC_EMOTE_STATE_DANCE = 10
NPC_EMOTE_ONESHOT_LAUGH = 11
NPC_EMOTE_ONESHOT_KNEEL = 16
NPC_EMOTE_ONESHOT_KISS = 17
NPC_EMOTE_ONESHOT_CRY = 18
NPC_EMOTE_ONESHOT_CHICKEN = 19
NPC_EMOTE_ONESHOT_BEG = 20
NPC_EMOTE_ONESHOT_APPLAUD = 21
NPC_EMOTE_ONESHOT_SHOUT_DNR = 22
NPC_EMOTE_ONESHOT_FLEX = 23
NPC_EMOTE_ONESHOT_SHY_DNR = 24
NPC_EMOTE_ONESHOT_POINT_DNR = 25
NPC_EMOTE_STATE_STAND = 26
NPC_EMOTE_STATE_READYUNARMED = 27
NPC_EMOTE_STATE_WORK_SHEATHED = 28
NPC_EMOTE_STATE_POINT_DNR = 29
NPC_EMOTE_STATE_NONE = 30
NPC_EMOTE_ONESHOT_WOUND = 33
NPC_EMOTE_ONESHOT_WOUNDCRITICAL = 34
NPC_EMOTE_ONESHOT_ATTACKUNARMED = 35
NPC_EMOTE_ONESHOT_ATTACK1H = 36
NPC_EMOTE_ONESHOT_ATTACK2HTIGHT = 37
NPC_EMOTE_ONESHOT_ATTACK2H_LOOSE = 38
NPC_EMOTE_ONESHOT_PARRYUNARMED = 39
NPC_EMOTE_ONESHOT_PARRYSHIELD = 43
NPC_EMOTE_ONESHOT_READYUNARMED = 44
NPC_EMOTE_ONESHOT_READY1H = 45
NPC_EMOTE_ONESHOT_READYBOW = 48
NPC_EMOTE_ONESHOT_SPELLPRECAST = 50
NPC_EMOTE_ONESHOT_SPELLCAST = 51
NPC_EMOTE_ONESHOT_BATTLEROAR = 53
NPC_EMOTE_ONESHOT_SPECIALATTACK1H = 54
NPC_EMOTE_ONESHOT_KICK = 60
NPC_EMOTE_ONESHOT_ATTACKTHROWN = 61
NPC_EMOTE_STATE_STUN = 64
NPC_EMOTE_STATE_DEAD = 65
NPC_EMOTE_ONESHOT_SALUTE = 66
NPC_EMOTE_STATE_KNEEL = 68
NPC_EMOTE_STATE_USESTANDING = 69
NPC_EMOTE_ONESHOT_WAVE_NOSHEATHE = 70
NPC_EMOTE_ONESHOT_CHEER_NOSHEATHE = 71
NPC_EMOTE_ONESHOT_EAT_NOSHEATHE = 92
NPC_EMOTE_STATE_STUN_NOSHEATHE = 93
NPC_EMOTE_ONESHOT_DANCE = 94
NPC_EMOTE_ONESHOT_WHISTLE = 104
NPC_EMOTE_ONESHOT_SALUTE_NOSHEATH = 113
NPC_EMOTE_STATE_USESTANDING_NOSHEATHE = 133
NPC_EMOTE_ONESHOT_LAUGH_NOSHEATHE = 153
NPC_EMOTE_STATE_WORK = 173
NPC_EMOTE_STATE_SPELLPRECAST = 193
NPC_EMOTE_ONESHOT_READYRIFLE = 213
NPC_EMOTE_STATE_READYRIFLE = 214
NPC_EMOTE_STATE_WORK_MINING = 233
NPC_EMOTE_STATE_WORK_CHOPWOOD = 234
NPC_EMOTE_STATE_APPLAUD = 253
NPC_EMOTE_ONESHOT_LIFTOFF = 254
NPC_EMOTE_ONESHOT_YES_DNR = 273
NPC_EMOTE_ONESHOT_NO_DNR = 274
NPC_EMOTE_ONESHOT_TRAIN_DNR = 275
NPC_EMOTE_ONESHOT_LAND = 293
NPC_EMOTE_STATE_AT_EASE = 313
NPC_EMOTE_STATE_READY1H = 333
NPC_EMOTE_STATE_SPELLKNEELSTART = 353
NPC_EMOTE_STAND_STATE_SUBMERGED = 373
NPC_EMOTE_ONESHOT_SUBMERGE = 374
NPC_EMOTE_STATE_READY2H = 375
NPC_EMOTE_STATE_READYBOW = 376
NPC_EMOTE_ONESHOT_MOUNTSPECIAL = 377
NPC_EMOTE_STATE_TALK = 378
NPC_EMOTE_STATE_FISHING = 379
NPC_EMOTE_ONESHOT_FISHING = 380
NPC_EMOTE_ONESHOT_LOOT = 381
NPC_EMOTE_STATE_WHIRLWIND = 382
NPC_EMOTE_STATE_DROWNED = 383
NPC_EMOTE_STATE_HOLD_BOW = 384
NPC_EMOTE_STATE_HOLD_RIFLE = 385
NPC_EMOTE_STATE_HOLD_THROWN = 386
NPC_EMOTE_ONESHOT_DROWN = 387
NPC_EMOTE_ONESHOT_STOMP = 388
NPC_EMOTE_ONESHOT_ATTACKOFF = 389
NPC_EMOTE_ONESHOT_ATTACKOFFPIERCE = 390
NPC_EMOTE_STATE_ROAR = 391
NPC_EMOTE_STATE_LAUGH = 392
NPC_EMOTE_ONESHOT_CREATURE_SPECIAL = 393
NPC_EMOTE_ONESHOT_JUMPLANDRUN = 394
NPC_EMOTE_ONESHOT_JUMPEND = 395
NPC_EMOTE_ONESHOT_TALK_NOSHEATHE = 396
NPC_EMOTE_ONESHOT_POINT_NOSHEATHE = 397
NPC_EMOTE_STATE_CANNIBALIZE = 398
NPC_EMOTE_ONESHOT_JUMPSTART = 399
NPC_EMOTE_STATE_DANCESPECIAL = 400
NPC_EMOTE_ONESHOT_DANCESPECIAL = 401
NPC_EMOTE_ONESHOT_CUSTOMSPELL01 = 402
NPC_EMOTE_ONESHOT_CUSTOMSPELL02 = 403
NPC_EMOTE_ONESHOT_CUSTOMSPELL03 = 404
NPC_EMOTE_ONESHOT_CUSTOMSPELL04 = 405
NPC_EMOTE_ONESHOT_CUSTOMSPELL05 = 406
NPC_EMOTE_ONESHOT_CUSTOMSPELL06 = 407
NPC_EMOTE_ONESHOT_CUSTOMSPELL07 = 408
NPC_EMOTE_ONESHOT_CUSTOMSPELL08 = 409
NPC_EMOTE_ONESHOT_CUSTOMSPELL09 = 410
NPC_EMOTE_ONESHOT_CUSTOMSPELL10 = 411
NPC_EMOTE_STATE_EXCLAIM = 412
NPC_EMOTE_STATE_DANCE_CUSTOM = 413
NPC_EMOTE_STATE_SIT_CHAIR_MED = 415
NPC_EMOTE_STATE_CUSTOM_SPELL_01 = 416
NPC_EMOTE_STATE_CUSTOM_SPELL_02 = 417
NPC_EMOTE_STATE_EAT = 418
NPC_EMOTE_STATE_CUSTOM_SPELL_04 = 419
NPC_EMOTE_STATE_CUSTOM_SPELL_03 = 420
NPC_EMOTE_STATE_CUSTOM_SPELL_05 = 421
NPC_EMOTE_STATE_SPELLEFFECT_HOLD = 422
NPC_EMOTE_STATE_EAT_NO_SHEATHE = 423
NPC_EMOTE_STATE_MOUNT = 424
NPC_EMOTE_STATE_READY2HL = 425
NPC_EMOTE_STATE_SIT_CHAIR_HIGH = 426
NPC_EMOTE_STATE_FALL = 427
NPC_EMOTE_STATE_LOOT = 428
NPC_EMOTE_STATE_SUBMERGED = 429
NPC_EMOTE_STATE_COWER = 431
NPC_EMOTE_ONESHOT_USESTANDING = 432
NPC_EMOTE_STATE_STEALTH_STAND = 433
NPC_EMOTE_ONESHOT_OMNICAST_GHOUL_W_SOUND = 434
NPC_EMOTE_ONESHOT_ATTACKBOW = 435
NPC_EMOTE_ONESHOT_ATTACKRIFLE = 436
NPC_EMOTE_STATE_SWIM_IDLE = 437
NPC_EMOTE_STATE_ATTACK_UNARMED = 438
NPC_EMOTE_ONESHOT_SPELLCAST_W_SOUND = 439
NPC_EMOTE_ONESHOT_DODGE = 440
NPC_EMOTE_ONESHOT_PARRY1H = 441
NPC_EMOTE_ONESHOT_PARRY2H = 442
NPC_EMOTE_ONESHOT_PARRY2HL = 443
NPC_EMOTE_STATE_FLYFALL = 444
NPC_EMOTE_ONESHOT_FLYDEATH = 445
NPC_EMOTE_STATE_FLY_FALL = 446
NPC_EMOTE_ONESHOT_FLY_SIT_GROUND_DOWN = 447
NPC_EMOTE_ONESHOT_FLY_SIT_GROUND_UP = 448
NPC_EMOTE_ONESHOT_EMERGE = 449
NPC_EMOTE_ONESHOT_DRAGONSPIT = 450
NPC_EMOTE_STATE_SPECIALUNARMED = 451
NPC_EMOTE_ONESHOT_FLYGRAB = 452
NPC_EMOTE_STATE_FLYGRABCLOSED = 453
NPC_EMOTE_ONESHOT_FLYGRABTHROWN = 454
NPC_EMOTE_STATE_FLY_SIT_GROUND = 455
NPC_EMOTE_STATE_WALKBACKWARDS = 456
NPC_EMOTE_ONESHOT_FLYTALK = 457
NPC_EMOTE_ONESHOT_FLYATTACK1H = 458
NPC_EMOTE_STATE_CUSTOMSPELL08 = 459
NPC_EMOTE_ONESHOT_FLY_DRAGONSPIT = 460
NPC_EMOTE_STATE_SIT_CHAIR_LOW = 461
NPC_EMOTE_ONE_SHOT_STUN = 462
NPC_EMOTE_ONESHOT_SPELLCAST_OMNI = 463
NPC_EMOTE_STATE_READYTHROWN = 465
NPC_EMOTE_ONESHOT_WORK_CHOPWOOD = 466
NPC_EMOTE_ONESHOT_WORK_MINING = 467
NPC_EMOTE_STATE_SPELL_CHANNEL_OMNI = 468
NPC_EMOTE_STATE_SPELL_CHANNEL_DIRECTED = 469
NPC_EMOTE_STAND_STATE_NONE = 470
NPC_EMOTE_STATE_READYJOUST = 471
NPC_EMOTE_STATE_STRANGULATE = 473
NPC_EMOTE_STATE_READYSPELLOMNI = 474
NPC_EMOTE_STATE_HOLD_JOUST = 475

# Creatures - Template
CREATURE_NPC_FLAGS_GOSSIP = 1
CREATURE_NPC_FLAGS_QUEST_GIVER = 2

# Quests - Template
QUEST_TYPE_ENABLED_AND_AUTO_ACCEPTED = 0
QUEST_TYPE_DISABLED = 1
QUEST_TYPE_ENABLED = 2
QUEST_TYPE_WORLD_QUEST = 3
QUEST_FLAGS_DAILY = 4096
QUEST_FLAGS_WEEKLY = 32768

# Quests - Template Addon
QUEST_FLAGS_REPEATABLE = 1

# Conditions _sources_ (where the condition is coming from)
CONDITION_SOURCE_TYPE_NONE = 0
CONDITION_SOURCE_TYPE_CREATURE_LOOT_TEMPLATE = 1
CONDITION_SOURCE_TYPE_DISENCHANT_LOOT_TEMPLATE = 2
CONDITION_SOURCE_TYPE_FISHING_LOOT_TEMPLATE = 3
CONDITION_SOURCE_TYPE_GAMEOBJECT_LOOT_TEMPLATE = 4
CONDITION_SOURCE_TYPE_ITEM_LOOT_TEMPLATE = 5
CONDITION_SOURCE_TYPE_MAIL_LOOT_TEMPLATE = 6
CONDITION_SOURCE_TYPE_MILLING_LOOT_TEMPLATE = 7
CONDITION_SOURCE_TYPE_PICKPOCKETING_LOOT_TEMPLATE = 8
CONDITION_SOURCE_TYPE_PROSPECTING_LOOT_TEMPLATE = 9
CONDITION_SOURCE_TYPE_REFERENCE_LOOT_TEMPLATE = 10
CONDITION_SOURCE_TYPE_SKINNING_LOOT_TEMPLATE = 11
CONDITION_SOURCE_TYPE_SPELL_LOOT_TEMPLATE = 12
CONDITION_SOURCE_TYPE_SPELL_IMPLICIT_TARGET = 13
CONDITION_SOURCE_TYPE_GOSSIP_MENU = 14
CONDITION_SOURCE_TYPE_GOSSIP_MENU_OPTION = 15
CONDITION_SOURCE_TYPE_CREATURE_TEMPLATE_VEHICLE = 16
CONDITION_SOURCE_TYPE_SPELL = 17
CONDITION_SOURCE_TYPE_SPELL_CLICK_EVENT = 18
CONDITION_SOURCE_TYPE_QUEST_AVAILABLE = 19
CONDITION_SOURCE_TYPE_UNUSED_20 = 20
CONDITION_SOURCE_TYPE_VEHICLE_SPELL = 21
CONDITION_SOURCE_TYPE_SMART_EVENT = 22
CONDITION_SOURCE_TYPE_NPC_VENDOR = 23
CONDITION_SOURCE_TYPE_SPELL_PROC = 24
CONDITION_SOURCE_TYPE_MAX = 27

# Conditions used in the `conditions` table
CONDITION_NONE = 0
CONDITION_AURA = 1
CONDITION_ITEM = 2
CONDITION_ITEM_EQUIPPED = 3
CONDITION_ZONEID = 4
CONDITION_REPUTATION_RANK = 5
CONDITION_TEAM = 6
CONDITION_SKILL = 7
CONDITION_QUESTREWARDED = 8
CONDITION_QUESTTAKEN = 9
CONDITION_DRUNKENSTATE = 10
CONDITION_WORLD_STATE = 11
CONDITION_ACTIVE_EVENT = 12
CONDITION_INSTANCE_INFO = 13
CONDITION_QUEST_NONE = 14
CONDITION_CLASS = 15
CONDITION_RACE = 16
CONDITION_ACHIEVEMENT = 17
CONDITION_TITLE = 18
CONDITION_SPAWNMASK = 19
CONDITION_GENDER = 20
CONDITION_UNIT_STATE = 21
CONDITION_MAPID = 22
CONDITION_AREAID = 23
CONDITION_CREATURE_TYPE = 24
CONDITION_SPELL = 25
CONDITION_PHASEMASK = 26
CONDITION_LEVEL = 27
CONDITION_QUEST_COMPLETE = 28
CONDITION_NEAR_CREATURE = 29
CONDITION_NEAR_GAMEOBJECT = 30
CONDITION_OBJECT_ENTRY_GUID = 31
CONDITION_TYPE_MASK = 32
CONDITION_RELATION_TO = 33
CONDITION_REACTION_TO = 34
CONDITION_DISTANCE_TO = 35
CONDITION_ALIVE = 36
CONDITION_HP_VAL = 37
CONDITION_HP_PCT = 38
CONDITION_REALM_ACHIEVEMENT = 39
CONDITION_IN_WATER = 40
CONDITION_STAND_STATE = 42
CONDITION_DAILY_QUEST_DONE = 43
CONDITION_CHARMED = 44
CONDITION_PET_TYPE = 45
CONDITION_TAXI = 46
CONDITION_QUESTSTATE = 47
CONDITION_QUEST_OBJECTIVE_PROGRESS = 48
CONDITION_MAX = 49

# Reputation ranks
REPUTATION_RANK_HATED = 1
REPUTATION_RANK_HOSTILE = 2
REPUTATION_RANK_UNFRIENDLY = 4
REPUTATION_RANK_NEUTRAL = 8
REPUTATION_RANK_FRIENDLY = 16
REPUTATION_RANK_HONORED = 32
REPUTATION_RANK_REVERED = 64
REPUTATION_RANK_EXALTED = 128

# Creature family types
CREATURE_FAMILY_WOLF = 1
CREATURE_FAMILY_OWL = 26
CREATURE_FAMILY_CAT = 2
CREATURE_FAMILY_WIND_SERPENT = 27
CREATURE_FAMILY_SPIDER = 3
CREATURE_FAMILY_REMOTE_CONTROL = 28
CREATURE_FAMILY_BEAR = 4
CREATURE_FAMILY_FELGUARD = 29
CREATURE_FAMILY_BOAR = 5
CREATURE_FAMILY_DRAGONHAWK = 30
CREATURE_FAMILY_CROCOLISK = 6
CREATURE_FAMILY_RAVAGER = 31
CREATURE_FAMILY_CARRION_BIRD = 7
CREATURE_FAMILY_WARP_STALKER = 32
CREATURE_FAMILY_CRAB = 8
CREATURE_FAMILY_SPOREBAT = 33
CREATURE_FAMILY_GORILLA = 9
CREATURE_FAMILY_NETHER_RAY = 34
CREATURE_FAMILY_RAPTOR = 11
CREATURE_FAMILY_SERPENT = 35
CREATURE_FAMILY_TALLSTRIDER = 12
CREATURE_FAMILY_MOTH = 37
CREATURE_FAMILY_FELHUNTER = 15
CREATURE_FAMILY_CHIMAERA = 38
CREATURE_FAMILY_VOIDWALKER = 16
CREATURE_FAMILY_DEVILSAUR = 39
CREATURE_FAMILY_SUCCUBUS = 17
CREATURE_FAMILY_GHOUL = 40
CREATURE_FAMILY_DOOMGUARD = 19
CREATURE_FAMILY_SILITHID = 41
CREATURE_FAMILY_SCORPID = 20
CREATURE_FAMILY_WORM = 42
CREATURE_FAMILY_TURTLE = 21
CREATURE_FAMILY_RHINO = 43
CREATURE_FAMILY_IMP = 23
CREATURE_FAMILY_WASP = 44
CREATURE_FAMILY_BAT = 24
CREATURE_FAMILY_CORE_HOUND = 45
CREATURE_FAMILY_HYENA = 25
CREATURE_FAMILY_SPIRIT_BEAST = 46

# Creature Types
CREATURE_TYPE_NONE = 0
CREATURE_TYPE_BEAST = 1
CREATURE_TYPE_DRAGONKIN = 2
CREATURE_TYPE_DEMON = 3
CREATURE_TYPE_ELEMENTAL = 4
CREATURE_TYPE_GIANT = 5
CREATURE_TYPE_UNDEAD = 6
CREATURE_TYPE_HUMANOID = 7
CREATURE_TYPE_CRITTER = 8
CREATURE_TYPE_MECHANICAL = 9
CREATURE_TYPE_NOT_SPECIFIED = 10
CREATURE_TYPE_TOTEM = 11
CREATURE_TYPE_NON_COMBAT_PET = 12
CREATURE_TYPE_GAS_CLOUD = 13

# Useful model IDs
MODEL_ID_RAT_WHITE = 2176
MODEL_ID_CHICKEN_WHITE = 304
MODEL_ID_CHICKEN_BROWN = 5369
MODEL_ID_CAT_BLACK = 5554
MODEL_ID_CAT_GREY_STRIPY = 5555
MODEL_ID_CAT_WHITE_GINGER = 5586

# Collectable pets
COLLECTABLE_CAT_CARRIER_CORNISH_REX = 8486
COLLECTABLE_CAT_CARRIER_ORANGE_TABBY = 8487
COLLECTABLE_CAT_CARRIER_SILVER_TABBY = 8488
COLLECTABLE_CAT_CARRIER_WHITE_KITTEN = 8489
COLLECTABLE_CAT_CARRIER_SIAMESE = 8490

# Playable Race IDs
RACE_HUMAN = 1
RACE_ORC = 2
RACE_DWARF = 4
RACE_NIGHT_ELF = 8
RACE_UNDEAD = 16
RACE_TAUREN = 32
RACE_GNOME = 64
RACE_TROLL = 128
RACE_GOBLIN = 256
RACE_BLOOD_ELF = 512
RACE_DRAENEI = 1024

# Factions - Alliance
FACTION_ALLIANCE_IRONFORGE = 57
FACTION_ALLIANCE_GNOMEREGAN_EXILES = 54
FACTION_ALLIANCE_DARNASSUS = 69
FACTION_ALLIANCE_STORMWIND = 72
# FACTION_ALLIANCE_: 509
# FACTION_ALLIANCE_: 730
# FACTION_ALLIANCE_: 890
# FACTION_ALLIANCE_: 930
# FACTION_ALLIANCE_: 946
# FACTION_ALLIANCE_: 978
# FACTION_ALLIANCE_: 1037
# FACTION_ALLIANCE_: 1050
# FACTION_ALLIANCE_: 1068
# FACTION_ALLIANCE_: 1094
# FACTION_ALLIANCE_: 1126

# Factions - Horde
FACTION_HORDE_DARKSPEAR_TROLLS = 530
FACTION_HORDE_THUNDER_BLUFF = 81
FACTION_HORDE_UNDERCITY = 68
FACTION_HORDE_ORGRIMMAR = 76
FACTION_HORDE_SILVERMOON_CITY = 911
# FACTION_HORDE_: 510
# FACTION_HORDE_: 729
# FACTION_HORDE_: 889
# FACTION_HORDE_: 947
# FACTION_HORDE_: 941
# FACTION_HORDE_: 1052
# FACTION_HORDE_: 1085
# FACTION_HORDE_: 1064
# FACTION_HORDE_: 1124
# FACTION_HORDE_: 1067

# Items - Consumable - First Aid
ITEM_CONSUMABLE_FIRSTAID_LINENBANDAGE = 1251

# Items - Consumable - Herbalism
ITEM_CONSUMABLE_HERBALISM_MINORHEALINGPOTION = 118

# Items - Consumable - Cooking
ITEM_CONSUMABLE_COOKING_SPICE_BREAD = 30816

# Items - Gathering - Skinning
ITEM_GATHERING_SKINNING_LEATHER_SCRAPS = 2934
ITEM_GATHERING_SKINNING_LIGHT_LEATHER = 2318

# Items - Crafting - Leatherworking
ITEM_CRAFTING_LEATHERWORKING_LIGHT_ARMOR_KIT = 2304
ITEM_CRAFTING_LEATHERWORKING_MEDIUM_ARMOR_KIT = 2313

# (Waypoint) Script Commands
# Used in waypoint_scripts and other tables
SCRIPT_COMMAND_TALK = 0 # Creature say/whisper/yell/textemote.
SCRIPT_COMMAND_EMOTE = 1 # Play emote on creature.
SCRIPT_COMMAND_FIELD_SET = 2 # Change the value at an index for the player.
SCRIPT_COMMAND_MOVE_TO = 3 # Relocate creature to a destination.
SCRIPT_COMMAND_FLAG_SET = 4 # Turns on bits on a flag field at an index for the player.
SCRIPT_COMMAND_FLAG_REMOVE = 5 # Turns off bits on a flag field at an index for the player.
SCRIPT_COMMAND_TELEPORT_TO = 6 # Teleports the player to a location.
SCRIPT_COMMAND_QUEST_EXPLORED = 7 # Satisfies the explore requirement for a quest.
SCRIPT_COMMAND_KILL_CREDIT = 8 # Gives kill credit to the player.
SCRIPT_COMMAND_RESPAWN_GAMEOBJECT = 9 # Spawns a despawned gameobject.
SCRIPT_COMMAND_TEMP_SUMMON_CREATURE = 10 # Temporarily summons a creature.
SCRIPT_COMMAND_OPEN_DOOR = 11 # Opens a door gameobject (type h1. 0).
SCRIPT_COMMAND_CLOSE_DOOR = 12 # Closes a door gameobject (type 0).
SCRIPT_COMMAND_ACTIVATE_OBJECT = 13 # Activates an object.
SCRIPT_COMMAND_REMOVE_AURA = 14 # Removes an aura due to a spell.
SCRIPT_COMMAND_CAST_SPELL = 15 # Casts a spell.
SCRIPT_COMMAND_PLAY_SOUND = 16 # Plays a sound.
SCRIPT_COMMAND_CREATE_ITEM = 17 # Creates specified amount of items for the player.
SCRIPT_COMMAND_DESPAWN_SELF = 18 # Forces creature to despawn.
SCRIPT_COMMAND_LOAD_PATH = 20 # Load path to unit, then unit starts waypoint movement.
SCRIPT_COMMAND_CALLSCRIPT_TO_UNIT = 21 # Calls script from one of *_scripts table with given unit as source.
SCRIPT_COMMAND_KILL = 22 # Changes state of the creature to dead and optionally removes its corpse.
SCRIPT_COMMAND_ORIENTATION = 30 # Changes unit's orientation (Used in Waypoint Scripts)
SCRIPT_COMMAND_EQUIP = 31 # Sets creature equipment.
SCRIPT_COMMAND_MODEL = 32 # Sets creature model.
SCRIPT_COMMAND_CLOSE_GOSSIP = 33 # Closes gossip window. This command is only used for Gossip Scripts.
SCRIPT_COMMAND_PLAYMOVIE = 34 # Plays movie.
SCRIPT_COMMAND_MOVEMENT = 35 # Change movement type.

# Shortcuts for waypoint delay timings
WAYPOINT_DELAY_1M = 60000 # 1 minute
WAYPOINT_DELAY_2M = 120000 # 2 minutes
WAYPOINT_DELAY_3M = 180000 # 3 minutes
WAYPOINT_DELAY_5M = 300000 # 5 minutes
WAYPOINT_DELAY_10M = 600000 # 10 minutes
WAYPOINT_DELAY_15M = 900000 # 15 minutes
WAYPOINT_DELAY_20M = 1200000 # 20 minutes
WAYPOINT_DELAY_30M = 1800000 # 30 minutes
WAYPOINT_DELAY_60M = 3600000 # 60 minutes
