def sql_new_durabilitycosts_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            weaponsubclasscost_1 = data['weaponsubclasscost_1'],
            weaponsubclasscost_2 = data['weaponsubclasscost_2'],
            weaponsubclasscost_3 = data['weaponsubclasscost_3'],
            weaponsubclasscost_4 = data['weaponsubclasscost_4'],
            weaponsubclasscost_5 = data['weaponsubclasscost_5'],
            weaponsubclasscost_6 = data['weaponsubclasscost_6'],
            weaponsubclasscost_7 = data['weaponsubclasscost_7'],
            weaponsubclasscost_8 = data['weaponsubclasscost_8'],
            weaponsubclasscost_9 = data['weaponsubclasscost_9'],
            weaponsubclasscost_10 = data['weaponsubclasscost_10'],
            weaponsubclasscost_11 = data['weaponsubclasscost_11'],
            weaponsubclasscost_12 = data['weaponsubclasscost_12'],
            weaponsubclasscost_13 = data['weaponsubclasscost_13'],
            weaponsubclasscost_14 = data['weaponsubclasscost_14'],
            weaponsubclasscost_15 = data['weaponsubclasscost_15'],
            weaponsubclasscost_16 = data['weaponsubclasscost_16'],
            weaponsubclasscost_17 = data['weaponsubclasscost_17'],
            weaponsubclasscost_18 = data['weaponsubclasscost_18'],
            weaponsubclasscost_19 = data['weaponsubclasscost_19'],
            weaponsubclasscost_20 = data['weaponsubclasscost_20'],
            weaponsubclasscost_21 = data['weaponsubclasscost_21'],
            armorsubclasscost_1 = data['armorsubclasscost_1'],
            armorsubclasscost_2 = data['armorsubclasscost_2'],
            armorsubclasscost_3 = data['armorsubclasscost_3'],
            armorsubclasscost_4 = data['armorsubclasscost_4'],
            armorsubclasscost_5 = data['armorsubclasscost_5'],
            armorsubclasscost_6 = data['armorsubclasscost_6'],
            armorsubclasscost_7 = data['armorsubclasscost_7'],
            armorsubclasscost_8 = data['armorsubclasscost_8'],
        )