def sql_new_wmoareatable_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            wmoid = data['wmoid'],
            namesetid = data['namesetid'],
            wmogroupid = data['wmogroupid'],
            soundproviderpref = data['soundproviderpref'],
            soundproviderprefunderwater = data['soundproviderprefunderwater'],
            ambienceid = data['ambienceid'],
            zonemusic = data['zonemusic'],
            introsound = data['introsound'],
            flags = data['flags'],
            areatableid = data['areatableid'],
            areaname_lang_enus = data['areaname_lang_enus'],
            areaname_lang_engb = data['areaname_lang_engb'],
            areaname_lang_kokr = data['areaname_lang_kokr'],
            areaname_lang_frfr = data['areaname_lang_frfr'],
            areaname_lang_dede = data['areaname_lang_dede'],
            areaname_lang_encn = data['areaname_lang_encn'],
            areaname_lang_zhcn = data['areaname_lang_zhcn'],
            areaname_lang_entw = data['areaname_lang_entw'],
            areaname_lang_zhtw = data['areaname_lang_zhtw'],
            areaname_lang_eses = data['areaname_lang_eses'],
            areaname_lang_esmx = data['areaname_lang_esmx'],
            areaname_lang_ruru = data['areaname_lang_ruru'],
            areaname_lang_ptpt = data['areaname_lang_ptpt'],
            areaname_lang_ptbr = data['areaname_lang_ptbr'],
            areaname_lang_itit = data['areaname_lang_itit'],
            areaname_lang_unk = data['areaname_lang_unk'],
            areaname_lang_mask = data['areaname_lang_mask'],
        )