
-- START barbershopstyle_dbc
SET
@id := {id},
@type := {type},
@displayname_lang_enus := "{displayname_lang_enus}",
@displayname_lang_engb := "{displayname_lang_engb}",
@displayname_lang_kokr := "{displayname_lang_kokr}",
@displayname_lang_frfr := "{displayname_lang_frfr}",
@displayname_lang_dede := "{displayname_lang_dede}",
@displayname_lang_encn := "{displayname_lang_encn}",
@displayname_lang_zhcn := "{displayname_lang_zhcn}",
@displayname_lang_entw := "{displayname_lang_entw}",
@displayname_lang_zhtw := "{displayname_lang_zhtw}",
@displayname_lang_eses := "{displayname_lang_eses}",
@displayname_lang_esmx := "{displayname_lang_esmx}",
@displayname_lang_ruru := "{displayname_lang_ruru}",
@displayname_lang_ptpt := "{displayname_lang_ptpt}",
@displayname_lang_ptbr := "{displayname_lang_ptbr}",
@displayname_lang_itit := "{displayname_lang_itit}",
@displayname_lang_unk := "{displayname_lang_unk}",
@displayname_lang_mask := {displayname_lang_mask},
@description_lang_enus := "{description_lang_enus}",
@description_lang_engb := "{description_lang_engb}",
@description_lang_kokr := "{description_lang_kokr}",
@description_lang_frfr := "{description_lang_frfr}",
@description_lang_dede := "{description_lang_dede}",
@description_lang_encn := "{description_lang_encn}",
@description_lang_zhcn := "{description_lang_zhcn}",
@description_lang_entw := "{description_lang_entw}",
@description_lang_zhtw := "{description_lang_zhtw}",
@description_lang_eses := "{description_lang_eses}",
@description_lang_esmx := "{description_lang_esmx}",
@description_lang_ruru := "{description_lang_ruru}",
@description_lang_ptpt := "{description_lang_ptpt}",
@description_lang_ptbr := "{description_lang_ptbr}",
@description_lang_itit := "{description_lang_itit}",
@description_lang_unk := "{description_lang_unk}",
@description_lang_mask := {description_lang_mask},
@cost_modifier := {cost_modifier},
@race := {race},
@sex := {sex},
@data := {data};

DELETE FROM barbershopstyle_dbc WHERE
    id=@id
;

INSERT INTO barbershopstyle_dbc (
    `id`,
    `type`,
    `displayname_lang_enus`,
    `displayname_lang_engb`,
    `displayname_lang_kokr`,
    `displayname_lang_frfr`,
    `displayname_lang_dede`,
    `displayname_lang_encn`,
    `displayname_lang_zhcn`,
    `displayname_lang_entw`,
    `displayname_lang_zhtw`,
    `displayname_lang_eses`,
    `displayname_lang_esmx`,
    `displayname_lang_ruru`,
    `displayname_lang_ptpt`,
    `displayname_lang_ptbr`,
    `displayname_lang_itit`,
    `displayname_lang_unk`,
    `displayname_lang_mask`,
    `description_lang_enus`,
    `description_lang_engb`,
    `description_lang_kokr`,
    `description_lang_frfr`,
    `description_lang_dede`,
    `description_lang_encn`,
    `description_lang_zhcn`,
    `description_lang_entw`,
    `description_lang_zhtw`,
    `description_lang_eses`,
    `description_lang_esmx`,
    `description_lang_ruru`,
    `description_lang_ptpt`,
    `description_lang_ptbr`,
    `description_lang_itit`,
    `description_lang_unk`,
    `description_lang_mask`,
    `cost_modifier`,
    `race`,
    `sex`,
    `data`
)
VALUES (
    @id,
    @type,
    @displayname_lang_enus,
    @displayname_lang_engb,
    @displayname_lang_kokr,
    @displayname_lang_frfr,
    @displayname_lang_dede,
    @displayname_lang_encn,
    @displayname_lang_zhcn,
    @displayname_lang_entw,
    @displayname_lang_zhtw,
    @displayname_lang_eses,
    @displayname_lang_esmx,
    @displayname_lang_ruru,
    @displayname_lang_ptpt,
    @displayname_lang_ptbr,
    @displayname_lang_itit,
    @displayname_lang_unk,
    @displayname_lang_mask,
    @description_lang_enus,
    @description_lang_engb,
    @description_lang_kokr,
    @description_lang_frfr,
    @description_lang_dede,
    @description_lang_encn,
    @description_lang_zhcn,
    @description_lang_entw,
    @description_lang_zhtw,
    @description_lang_eses,
    @description_lang_esmx,
    @description_lang_ruru,
    @description_lang_ptpt,
    @description_lang_ptbr,
    @description_lang_itit,
    @description_lang_unk,
    @description_lang_mask,
    @cost_modifier,
    @race,
    @sex,
    @data
);
-- EOF barbershopstyle_dbc