
-- START battlemasterlist_dbc
SET
@id := {id},
@mapid_1 := {mapid_1},
@mapid_2 := {mapid_2},
@mapid_3 := {mapid_3},
@mapid_4 := {mapid_4},
@mapid_5 := {mapid_5},
@mapid_6 := {mapid_6},
@mapid_7 := {mapid_7},
@mapid_8 := {mapid_8},
@instancetype := {instancetype},
@groupsallowed := {groupsallowed},
@name_lang_enus := "{name_lang_enus}",
@name_lang_engb := "{name_lang_engb}",
@name_lang_kokr := "{name_lang_kokr}",
@name_lang_frfr := "{name_lang_frfr}",
@name_lang_dede := "{name_lang_dede}",
@name_lang_encn := "{name_lang_encn}",
@name_lang_zhcn := "{name_lang_zhcn}",
@name_lang_entw := "{name_lang_entw}",
@name_lang_zhtw := "{name_lang_zhtw}",
@name_lang_eses := "{name_lang_eses}",
@name_lang_esmx := "{name_lang_esmx}",
@name_lang_ruru := "{name_lang_ruru}",
@name_lang_ptpt := "{name_lang_ptpt}",
@name_lang_ptbr := "{name_lang_ptbr}",
@name_lang_itit := "{name_lang_itit}",
@name_lang_unk := "{name_lang_unk}",
@name_lang_mask := {name_lang_mask},
@maxgroupsize := {maxgroupsize},
@holidayworldstate := {holidayworldstate},
@minlevel := {minlevel},
@maxlevel := {maxlevel};

DELETE FROM battlemasterlist_dbc WHERE
    id=@id
;

INSERT INTO battlemasterlist_dbc (
    `id`,
    `mapid_1`,
    `mapid_2`,
    `mapid_3`,
    `mapid_4`,
    `mapid_5`,
    `mapid_6`,
    `mapid_7`,
    `mapid_8`,
    `instancetype`,
    `groupsallowed`,
    `name_lang_enus`,
    `name_lang_engb`,
    `name_lang_kokr`,
    `name_lang_frfr`,
    `name_lang_dede`,
    `name_lang_encn`,
    `name_lang_zhcn`,
    `name_lang_entw`,
    `name_lang_zhtw`,
    `name_lang_eses`,
    `name_lang_esmx`,
    `name_lang_ruru`,
    `name_lang_ptpt`,
    `name_lang_ptbr`,
    `name_lang_itit`,
    `name_lang_unk`,
    `name_lang_mask`,
    `maxgroupsize`,
    `holidayworldstate`,
    `minlevel`,
    `maxlevel`
)
VALUES (
    @id,
    @mapid_1,
    @mapid_2,
    @mapid_3,
    @mapid_4,
    @mapid_5,
    @mapid_6,
    @mapid_7,
    @mapid_8,
    @instancetype,
    @groupsallowed,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @maxgroupsize,
    @holidayworldstate,
    @minlevel,
    @maxlevel
);
-- EOF battlemasterlist_dbc