
-- START itemrandomsuffix_dbc
SET
@id := {id},
@name_lang_enus := "{name_lang_enus}",
@name_lang_engb := "{name_lang_engb}",
@name_lang_kokr := "{name_lang_kokr}",
@name_lang_frfr := "{name_lang_frfr}",
@name_lang_dede := "{name_lang_dede}",
@name_lang_encn := "{name_lang_encn}",
@name_lang_zhcn := "{name_lang_zhcn}",
@name_lang_entw := "{name_lang_entw}",
@name_lang_zhtw := "{name_lang_zhtw}",
@name_lang_eses := "{name_lang_eses}",
@name_lang_esmx := "{name_lang_esmx}",
@name_lang_ruru := "{name_lang_ruru}",
@name_lang_ptpt := "{name_lang_ptpt}",
@name_lang_ptbr := "{name_lang_ptbr}",
@name_lang_itit := "{name_lang_itit}",
@name_lang_unk := "{name_lang_unk}",
@name_lang_mask := {name_lang_mask},
@internalname := "{internalname}",
@enchantment_1 := {enchantment_1},
@enchantment_2 := {enchantment_2},
@enchantment_3 := {enchantment_3},
@enchantment_4 := {enchantment_4},
@enchantment_5 := {enchantment_5},
@allocationpct_1 := {allocationpct_1},
@allocationpct_2 := {allocationpct_2},
@allocationpct_3 := {allocationpct_3},
@allocationpct_4 := {allocationpct_4},
@allocationpct_5 := {allocationpct_5};

DELETE FROM itemrandomsuffix_dbc WHERE
    id=@id
;

INSERT INTO itemrandomsuffix_dbc (
    `id`,
    `name_lang_enus`,
    `name_lang_engb`,
    `name_lang_kokr`,
    `name_lang_frfr`,
    `name_lang_dede`,
    `name_lang_encn`,
    `name_lang_zhcn`,
    `name_lang_entw`,
    `name_lang_zhtw`,
    `name_lang_eses`,
    `name_lang_esmx`,
    `name_lang_ruru`,
    `name_lang_ptpt`,
    `name_lang_ptbr`,
    `name_lang_itit`,
    `name_lang_unk`,
    `name_lang_mask`,
    `internalname`,
    `enchantment_1`,
    `enchantment_2`,
    `enchantment_3`,
    `enchantment_4`,
    `enchantment_5`,
    `allocationpct_1`,
    `allocationpct_2`,
    `allocationpct_3`,
    `allocationpct_4`,
    `allocationpct_5`
)
VALUES (
    @id,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @internalname,
    @enchantment_1,
    @enchantment_2,
    @enchantment_3,
    @enchantment_4,
    @enchantment_5,
    @allocationpct_1,
    @allocationpct_2,
    @allocationpct_3,
    @allocationpct_4,
    @allocationpct_5
);
-- EOF itemrandomsuffix_dbc