
-- START soundentries_dbc
SET
@id := {id},
@soundtype := {soundtype},
@name := "{name}",
@file_1 := "{file_1}",
@file_2 := "{file_2}",
@file_3 := "{file_3}",
@file_4 := "{file_4}",
@file_5 := "{file_5}",
@file_6 := "{file_6}",
@file_7 := "{file_7}",
@file_8 := "{file_8}",
@file_9 := "{file_9}",
@file_10 := "{file_10}",
@freq_1 := {freq_1},
@freq_2 := {freq_2},
@freq_3 := {freq_3},
@freq_4 := {freq_4},
@freq_5 := {freq_5},
@freq_6 := {freq_6},
@freq_7 := {freq_7},
@freq_8 := {freq_8},
@freq_9 := {freq_9},
@freq_10 := {freq_10},
@directorybase := "{directorybase}",
@volumefloat := {volumefloat},
@flags := {flags},
@mindistance := {mindistance},
@distancecutoff := {distancecutoff},
@eaxdef := {eaxdef},
@soundentriesadvancedid := {soundentriesadvancedid};

DELETE FROM soundentries_dbc WHERE
    id=@id
;

INSERT INTO soundentries_dbc (
    `id`,
    `soundtype`,
    `name`,
    `file_1`,
    `file_2`,
    `file_3`,
    `file_4`,
    `file_5`,
    `file_6`,
    `file_7`,
    `file_8`,
    `file_9`,
    `file_10`,
    `freq_1`,
    `freq_2`,
    `freq_3`,
    `freq_4`,
    `freq_5`,
    `freq_6`,
    `freq_7`,
    `freq_8`,
    `freq_9`,
    `freq_10`,
    `directorybase`,
    `volumefloat`,
    `flags`,
    `mindistance`,
    `distancecutoff`,
    `eaxdef`,
    `soundentriesadvancedid`
)
VALUES (
    @id,
    @soundtype,
    @name,
    @file_1,
    @file_2,
    @file_3,
    @file_4,
    @file_5,
    @file_6,
    @file_7,
    @file_8,
    @file_9,
    @file_10,
    @freq_1,
    @freq_2,
    @freq_3,
    @freq_4,
    @freq_5,
    @freq_6,
    @freq_7,
    @freq_8,
    @freq_9,
    @freq_10,
    @directorybase,
    @volumefloat,
    @flags,
    @mindistance,
    @distancecutoff,
    @eaxdef,
    @soundentriesadvancedid
);
-- EOF soundentries_dbc