
-- START vehicle_dbc
SET
@id := {id},
@flags := {flags},
@turnspeed := {turnspeed},
@pitchspeed := {pitchspeed},
@pitchmin := {pitchmin},
@pitchmax := {pitchmax},
@seatid_1 := {seatid_1},
@seatid_2 := {seatid_2},
@seatid_3 := {seatid_3},
@seatid_4 := {seatid_4},
@seatid_5 := {seatid_5},
@seatid_6 := {seatid_6},
@seatid_7 := {seatid_7},
@seatid_8 := {seatid_8},
@mouselookoffsetpitch := {mouselookoffsetpitch},
@camerafadedistscalarmin := {camerafadedistscalarmin},
@camerafadedistscalarmax := {camerafadedistscalarmax},
@camerapitchoffset := {camerapitchoffset},
@facinglimitright := {facinglimitright},
@facinglimitleft := {facinglimitleft},
@mssltrgtturnlingering := {mssltrgtturnlingering},
@mssltrgtpitchlingering := {mssltrgtpitchlingering},
@mssltrgtmouselingering := {mssltrgtmouselingering},
@mssltrgtendopacity := {mssltrgtendopacity},
@mssltrgtarcspeed := {mssltrgtarcspeed},
@mssltrgtarcrepeat := {mssltrgtarcrepeat},
@mssltrgtarcwidth := {mssltrgtarcwidth},
@mssltrgtimpactradius_1 := {mssltrgtimpactradius_1},
@mssltrgtimpactradius_2 := {mssltrgtimpactradius_2},
@mssltrgtarctexture := "{mssltrgtarctexture}",
@mssltrgtimpacttexture := "{mssltrgtimpacttexture}",
@mssltrgtimpactmodel_1 := "{mssltrgtimpactmodel_1}",
@mssltrgtimpactmodel_2 := "{mssltrgtimpactmodel_2}",
@camerayawoffset := {camerayawoffset},
@uilocomotiontype := {uilocomotiontype},
@mssltrgtimpacttexradius := {mssltrgtimpacttexradius},
@vehicleuiindicatorid := {vehicleuiindicatorid},
@powerdisplayid_1 := {powerdisplayid_1},
@powerdisplayid_2 := {powerdisplayid_2},
@powerdisplayid_3 := {powerdisplayid_3};

DELETE FROM vehicle_dbc WHERE
    id=@id
;

INSERT INTO vehicle_dbc (
    `id`,
    `flags`,
    `turnspeed`,
    `pitchspeed`,
    `pitchmin`,
    `pitchmax`,
    `seatid_1`,
    `seatid_2`,
    `seatid_3`,
    `seatid_4`,
    `seatid_5`,
    `seatid_6`,
    `seatid_7`,
    `seatid_8`,
    `mouselookoffsetpitch`,
    `camerafadedistscalarmin`,
    `camerafadedistscalarmax`,
    `camerapitchoffset`,
    `facinglimitright`,
    `facinglimitleft`,
    `mssltrgtturnlingering`,
    `mssltrgtpitchlingering`,
    `mssltrgtmouselingering`,
    `mssltrgtendopacity`,
    `mssltrgtarcspeed`,
    `mssltrgtarcrepeat`,
    `mssltrgtarcwidth`,
    `mssltrgtimpactradius_1`,
    `mssltrgtimpactradius_2`,
    `mssltrgtarctexture`,
    `mssltrgtimpacttexture`,
    `mssltrgtimpactmodel_1`,
    `mssltrgtimpactmodel_2`,
    `camerayawoffset`,
    `uilocomotiontype`,
    `mssltrgtimpacttexradius`,
    `vehicleuiindicatorid`,
    `powerdisplayid_1`,
    `powerdisplayid_2`,
    `powerdisplayid_3`
)
VALUES (
    @id,
    @flags,
    @turnspeed,
    @pitchspeed,
    @pitchmin,
    @pitchmax,
    @seatid_1,
    @seatid_2,
    @seatid_3,
    @seatid_4,
    @seatid_5,
    @seatid_6,
    @seatid_7,
    @seatid_8,
    @mouselookoffsetpitch,
    @camerafadedistscalarmin,
    @camerafadedistscalarmax,
    @camerapitchoffset,
    @facinglimitright,
    @facinglimitleft,
    @mssltrgtturnlingering,
    @mssltrgtpitchlingering,
    @mssltrgtmouselingering,
    @mssltrgtendopacity,
    @mssltrgtarcspeed,
    @mssltrgtarcrepeat,
    @mssltrgtarcwidth,
    @mssltrgtimpactradius_1,
    @mssltrgtimpactradius_2,
    @mssltrgtarctexture,
    @mssltrgtimpacttexture,
    @mssltrgtimpactmodel_1,
    @mssltrgtimpactmodel_2,
    @camerayawoffset,
    @uilocomotiontype,
    @mssltrgtimpacttexradius,
    @vehicleuiindicatorid,
    @powerdisplayid_1,
    @powerdisplayid_2,
    @powerdisplayid_3
);
-- EOF vehicle_dbc