
-- START achievement_criteria_dbc
SET
@id := {id},
@achievement_id := {achievement_id},
@type := {type},
@asset_id := {asset_id},
@quantity := {quantity},
@start_event := {start_event},
@start_asset := {start_asset},
@fail_event := {fail_event},
@fail_asset := {fail_asset},
@description_lang_enus := '{description_lang_enus}',
@description_lang_engb := '{description_lang_engb}',
@description_lang_kokr := '{description_lang_kokr}',
@description_lang_frfr := '{description_lang_frfr}',
@description_lang_dede := '{description_lang_dede}',
@description_lang_encn := '{description_lang_encn}',
@description_lang_zhcn := '{description_lang_zhcn}',
@description_lang_entw := '{description_lang_entw}',
@description_lang_zhtw := '{description_lang_zhtw}',
@description_lang_eses := '{description_lang_eses}',
@description_lang_esmx := '{description_lang_esmx}',
@description_lang_ruru := '{description_lang_ruru}',
@description_lang_ptpt := '{description_lang_ptpt}',
@description_lang_ptbr := '{description_lang_ptbr}',
@description_lang_itit := '{description_lang_itit}',
@description_lang_unk := '{description_lang_unk}',
@description_lang_mask := {description_lang_mask},
@flags := {flags},
@timer_start_event := {timer_start_event},
@timer_asset_id := {timer_asset_id},
@timer_time := {timer_time},
@ui_order := {ui_order};

DELETE FROM achievement_criteria_dbc WHERE
    id=@id
;

INSERT INTO achievement_criteria_dbc (
    id,
    achievement_id,
    type,
    asset_id,
    quantity,
    start_event,
    start_asset,
    fail_event,
    fail_asset,
    description_lang_enus,
    description_lang_engb,
    description_lang_kokr,
    description_lang_frfr,
    description_lang_dede,
    description_lang_encn,
    description_lang_zhcn,
    description_lang_entw,
    description_lang_zhtw,
    description_lang_eses,
    description_lang_esmx,
    description_lang_ruru,
    description_lang_ptpt,
    description_lang_ptbr,
    description_lang_itit,
    description_lang_unk,
    description_lang_mask,
    flags,
    timer_start_event,
    timer_asset_id,
    timer_time,
    ui_order
)
VALUES (
    @id,
    @achievement_id,
    @type,
    @asset_id,
    @quantity,
    @start_event,
    @start_asset,
    @fail_event,
    @fail_asset,
    @description_lang_enus,
    @description_lang_engb,
    @description_lang_kokr,
    @description_lang_frfr,
    @description_lang_dede,
    @description_lang_encn,
    @description_lang_zhcn,
    @description_lang_entw,
    @description_lang_zhtw,
    @description_lang_eses,
    @description_lang_esmx,
    @description_lang_ruru,
    @description_lang_ptpt,
    @description_lang_ptbr,
    @description_lang_itit,
    @description_lang_unk,
    @description_lang_mask,
    @flags,
    @timer_start_event,
    @timer_asset_id,
    @timer_time,
    @ui_order
);
-- EOF achievement_criteria_dbc