-- BEGIN: chartitles_dbc
SET
@id := {id},
@condition_id := {condition_id},
@name_lang_enus := '{name_lang_enus}',
@name_lang_engb := '{name_lang_engb}',
@name_lang_kokr := '{name_lang_kokr}',
@name_lang_frfr := '{name_lang_frfr}',
@name_lang_dede := '{name_lang_dede}',
@name_lang_encn := '{name_lang_encn}',
@name_lang_zhcn := '{name_lang_zhcn}',
@name_lang_entw := '{name_lang_entw}',
@name_lang_zhtw := '{name_lang_zhtw}',
@name_lang_eses := '{name_lang_eses}',
@name_lang_esmx := '{name_lang_esmx}',
@name_lang_ruru := '{name_lang_ruru}',
@name_lang_ptpt := '{name_lang_ptpt}',
@name_lang_ptbr := '{name_lang_ptbr}',
@name_lang_itit := '{name_lang_itit}',
@name_lang_unk := '{name_lang_unk}',
@name_lang_mask := {name_lang_mask},
@name1_lang_enus := '{name1_lang_enus}',
@name1_lang_engb := '{name1_lang_engb}',
@name1_lang_kokr := '{name1_lang_kokr}',
@name1_lang_frfr := '{name1_lang_frfr}',
@name1_lang_dede := '{name1_lang_dede}',
@name1_lang_encn := '{name1_lang_encn}',
@name1_lang_zhcn := '{name1_lang_zhcn}',
@name1_lang_entw := '{name1_lang_entw}',
@name1_lang_zhtw := '{name1_lang_zhtw}',
@name1_lang_eses := '{name1_lang_eses}',
@name1_lang_esmx := '{name1_lang_esmx}',
@name1_lang_ruru := '{name1_lang_ruru}',
@name1_lang_ptpt := '{name1_lang_ptpt}',
@name1_lang_ptbr := '{name1_lang_ptbr}',
@name1_lang_itit := '{name1_lang_itit}',
@name1_lang_unk := '{name1_lang_unk}',
@name1_lang_mask := {name1_lang_mask},
@mask_id := {mask_id};

DELETE FROM chartitles_dbc WHERE
    id=@id
;

INSERT INTO chartitles_dbc (
    id,
    condition_id,
    name_lang_enus,
    name_lang_engb,
    name_lang_kokr,
    name_lang_frfr,
    name_lang_dede,
    name_lang_encn,
    name_lang_zhcn,
    name_lang_entw,
    name_lang_zhtw,
    name_lang_eses,
    name_lang_esmx,
    name_lang_ruru,
    name_lang_ptpt,
    name_lang_ptbr,
    name_lang_itit,
    name_lang_unk,
    name_lang_mask,
    name1_lang_enus,
    name1_lang_engb,
    name1_lang_kokr,
    name1_lang_frfr,
    name1_lang_dede,
    name1_lang_encn,
    name1_lang_zhcn,
    name1_lang_entw,
    name1_lang_zhtw,
    name1_lang_eses,
    name1_lang_esmx,
    name1_lang_ruru,
    name1_lang_ptpt,
    name1_lang_ptbr,
    name1_lang_itit,
    name1_lang_unk,
    name1_lang_mask,
    mask_id
)
VALUES (
    @id,
    @condition_id,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @name1_lang_enus,
    @name1_lang_engb,
    @name1_lang_kokr,
    @name1_lang_frfr,
    @name1_lang_dede,
    @name1_lang_encn,
    @name1_lang_zhcn,
    @name1_lang_entw,
    @name1_lang_zhtw,
    @name1_lang_eses,
    @name1_lang_esmx,
    @name1_lang_ruru,
    @name1_lang_ptpt,
    @name1_lang_ptbr,
    @name1_lang_itit,
    @name1_lang_unk,
    @name1_lang_mask,
    @mask_id
);

-- END: chartitles_dbc