-- BEGIN: creature
SET
@guid := {guid},
@id1 := {id1},
@id2 := {id2},
@id3 := {id3},
@map := {map},
@zoneid := {zoneid},
@areaid := {areaid},
@spawnmask := {spawnmask},
@phasemask := {phasemask},
@equipment_id := {equipment_id},
@position_x := {position_x},
@position_y := {position_y},
@position_z := {position_z},
@orientation := {orientation},
@spawntimesecs := {spawntimesecs},
@wander_distance := {wander_distance},
@currentwaypoint := {currentwaypoint},
@curhealth := {curhealth},
@curmana := {curmana},
@movementtype := {movementtype},
@npcflag := {npcflag},
@unit_flags := {unit_flags},
@dynamicflags := {dynamicflags},
@scriptname := '{scriptname}',
@verifiedbuild := {verifiedbuild},
@createobject := {createobject},
@comment := '{comment}';

DELETE FROM creature WHERE
    guid=@guid
;

INSERT INTO creature (
    guid,
    id1,
    id2,
    id3,
    map,
    zoneid,
    areaid,
    spawnmask,
    phasemask,
    equipment_id,
    position_x,
    position_y,
    position_z,
    orientation,
    spawntimesecs,
    wander_distance,
    currentwaypoint,
    curhealth,
    curmana,
    movementtype,
    npcflag,
    unit_flags,
    dynamicflags,
    scriptname,
    verifiedbuild,
    createobject,
    comment
)
VALUES (
    @guid,
    @id1,
    @id2,
    @id3,
    @map,
    @zoneid,
    @areaid,
    @spawnmask,
    @phasemask,
    @equipment_id,
    @position_x,
    @position_y,
    @position_z,
    @orientation,
    @spawntimesecs,
    @wander_distance,
    @currentwaypoint,
    @curhealth,
    @curmana,
    @movementtype,
    @npcflag,
    @unit_flags,
    @dynamicflags,
    @scriptname,
    @verifiedbuild,
    @createobject,
    @comment
);

-- END: creature