
-- START creature_template
SET
@entry := {entry},
@difficulty_entry_1 := {difficulty_entry_1},
@difficulty_entry_2 := {difficulty_entry_2},
@difficulty_entry_3 := {difficulty_entry_3},
@killcredit1 := {killcredit1},
@killcredit2 := {killcredit2},
@modelid1 := {modelid1},
@modelid2 := {modelid2},
@modelid3 := {modelid3},
@modelid4 := {modelid4},
@name := '{name}',
@subname := '{subname}',
@iconname := '{iconname}',
@gossip_menu_id := {gossip_menu_id},
@minlevel := {minlevel},
@maxlevel := {maxlevel},
@exp := {exp},
@faction := {faction},
@npcflag := {npcflag},
@speed_walk := {speed_walk},
@speed_run := {speed_run},
@speed_swim := {speed_swim},
@speed_flight := {speed_flight},
@detection_range := {detection_range},
@scale := {scale},
@rank := {rank},
@dmgschool := {dmgschool},
@damagemodifier := {damagemodifier},
@baseattacktime := {baseattacktime},
@rangeattacktime := {rangeattacktime},
@basevariance := {basevariance},
@rangevariance := {rangevariance},
@unit_class := {unit_class},
@unit_flags := {unit_flags},
@unit_flags2 := {unit_flags2},
@dynamicflags := {dynamicflags},
@family := {family},
@trainer_type := {trainer_type},
@trainer_spell := {trainer_spell},
@trainer_class := {trainer_class},
@trainer_race := {trainer_race},
@type := {type},
@type_flags := {type_flags},
@lootid := {lootid},
@pickpocketloot := {pickpocketloot},
@skinloot := {skinloot},
@petspelldataid := {petspelldataid},
@vehicleid := {vehicleid},
@mingold := {mingold},
@maxgold := {maxgold},
@ainame := '{ainame}',
@movementtype := {movementtype},
@hoverheight := {hoverheight},
@healthmodifier := {healthmodifier},
@manamodifier := {manamodifier},
@armormodifier := {armormodifier},
@experiencemodifier := {experiencemodifier},
@racialleader := {racialleader},
@movementid := {movementid},
@regenhealth := {regenhealth},
@mechanic_immune_mask := {mechanic_immune_mask},
@spell_school_immune_mask := {spell_school_immune_mask},
@flags_extra := {flags_extra},
@scriptname := '{scriptname}',
@verifiedbuild := {verifiedbuild};

DELETE FROM creature_template WHERE
    entry=@entry
;

INSERT INTO creature_template (
    entry,
    difficulty_entry_1,
    difficulty_entry_2,
    difficulty_entry_3,
    killcredit1,
    killcredit2,
    modelid1,
    modelid2,
    modelid3,
    modelid4,
    name,
    subname,
    iconname,
    gossip_menu_id,
    minlevel,
    maxlevel,
    exp,
    faction,
    npcflag,
    speed_walk,
    speed_run,
    speed_swim,
    speed_flight,
    detection_range,
    scale,
    rank,
    dmgschool,
    damagemodifier,
    baseattacktime,
    rangeattacktime,
    basevariance,
    rangevariance,
    unit_class,
    unit_flags,
    unit_flags2,
    dynamicflags,
    family,
    trainer_type,
    trainer_spell,
    trainer_class,
    trainer_race,
    type,
    type_flags,
    lootid,
    pickpocketloot,
    skinloot,
    petspelldataid,
    vehicleid,
    mingold,
    maxgold,
    ainame,
    movementtype,
    hoverheight,
    healthmodifier,
    manamodifier,
    armormodifier,
    experiencemodifier,
    racialleader,
    movementid,
    regenhealth,
    mechanic_immune_mask,
    spell_school_immune_mask,
    flags_extra,
    scriptname,
    verifiedbuild
)
VALUES (
    @entry,
    @difficulty_entry_1,
    @difficulty_entry_2,
    @difficulty_entry_3,
    @killcredit1,
    @killcredit2,
    @modelid1,
    @modelid2,
    @modelid3,
    @modelid4,
    @name,
    @subname,
    @iconname,
    @gossip_menu_id,
    @minlevel,
    @maxlevel,
    @exp,
    @faction,
    @npcflag,
    @speed_walk,
    @speed_run,
    @speed_swim,
    @speed_flight,
    @detection_range,
    @scale,
    @rank,
    @dmgschool,
    @damagemodifier,
    @baseattacktime,
    @rangeattacktime,
    @basevariance,
    @rangevariance,
    @unit_class,
    @unit_flags,
    @unit_flags2,
    @dynamicflags,
    @family,
    @trainer_type,
    @trainer_spell,
    @trainer_class,
    @trainer_race,
    @type,
    @type_flags,
    @lootid,
    @pickpocketloot,
    @skinloot,
    @petspelldataid,
    @vehicleid,
    @mingold,
    @maxgold,
    @ainame,
    @movementtype,
    @hoverheight,
    @healthmodifier,
    @manamodifier,
    @armormodifier,
    @experiencemodifier,
    @racialleader,
    @movementid,
    @regenhealth,
    @mechanic_immune_mask,
    @spell_school_immune_mask,
    @flags_extra,
    @scriptname,
    @verifiedbuild
);
-- EOF creature_template