
-- START creaturemodeldata_dbc
SET
@id := {id},
@flags := {flags},
@modelname := '{modelname}',
@sizeclass := {sizeclass},
@modelscale := {modelscale},
@bloodid := {bloodid},
@footprinttextureid := {footprinttextureid},
@footprinttexturelength := {footprinttexturelength},
@footprinttexturewidth := {footprinttexturewidth},
@footprintparticlescale := {footprintparticlescale},
@foleymaterialid := {foleymaterialid},
@footstepshakesize := {footstepshakesize},
@deaththudshakesize := {deaththudshakesize},
@soundid := {soundid},
@collisionwidth := {collisionwidth},
@collisionheight := {collisionheight},
@mountheight := {mountheight},
@geoboxminx := {geoboxminx},
@geoboxminy := {geoboxminy},
@geoboxminz := {geoboxminz},
@geoboxmaxx := {geoboxmaxx},
@geoboxmaxy := {geoboxmaxy},
@geoboxmaxz := {geoboxmaxz},
@worldeffectscale := {worldeffectscale},
@attachedeffectscale := {attachedeffectscale},
@missilecollisionradius := {missilecollisionradius},
@missilecollisionpush := {missilecollisionpush},
@missilecollisionraise := {missilecollisionraise};

DELETE FROM creaturemodeldata_dbc WHERE
    id=@id
;

INSERT INTO creaturemodeldata_dbc (
    id,
    flags,
    modelname,
    sizeclass,
    modelscale,
    bloodid,
    footprinttextureid,
    footprinttexturelength,
    footprinttexturewidth,
    footprintparticlescale,
    foleymaterialid,
    footstepshakesize,
    deaththudshakesize,
    soundid,
    collisionwidth,
    collisionheight,
    mountheight,
    geoboxminx,
    geoboxminy,
    geoboxminz,
    geoboxmaxx,
    geoboxmaxy,
    geoboxmaxz,
    worldeffectscale,
    attachedeffectscale,
    missilecollisionradius,
    missilecollisionpush,
    missilecollisionraise
)
VALUES (
    @id,
    @flags,
    @modelname,
    @sizeclass,
    @modelscale,
    @bloodid,
    @footprinttextureid,
    @footprinttexturelength,
    @footprinttexturewidth,
    @footprintparticlescale,
    @foleymaterialid,
    @footstepshakesize,
    @deaththudshakesize,
    @soundid,
    @collisionwidth,
    @collisionheight,
    @mountheight,
    @geoboxminx,
    @geoboxminy,
    @geoboxminz,
    @geoboxmaxx,
    @geoboxmaxy,
    @geoboxmaxz,
    @worldeffectscale,
    @attachedeffectscale,
    @missilecollisionradius,
    @missilecollisionpush,
    @missilecollisionraise
);
-- EOF creaturemodeldata_dbc