-- BEGIN: durabilitycosts_dbc
SET
@id := {id},
@weaponsubclasscost_1 := {weaponsubclasscost_1},
@weaponsubclasscost_2 := {weaponsubclasscost_2},
@weaponsubclasscost_3 := {weaponsubclasscost_3},
@weaponsubclasscost_4 := {weaponsubclasscost_4},
@weaponsubclasscost_5 := {weaponsubclasscost_5},
@weaponsubclasscost_6 := {weaponsubclasscost_6},
@weaponsubclasscost_7 := {weaponsubclasscost_7},
@weaponsubclasscost_8 := {weaponsubclasscost_8},
@weaponsubclasscost_9 := {weaponsubclasscost_9},
@weaponsubclasscost_10 := {weaponsubclasscost_10},
@weaponsubclasscost_11 := {weaponsubclasscost_11},
@weaponsubclasscost_12 := {weaponsubclasscost_12},
@weaponsubclasscost_13 := {weaponsubclasscost_13},
@weaponsubclasscost_14 := {weaponsubclasscost_14},
@weaponsubclasscost_15 := {weaponsubclasscost_15},
@weaponsubclasscost_16 := {weaponsubclasscost_16},
@weaponsubclasscost_17 := {weaponsubclasscost_17},
@weaponsubclasscost_18 := {weaponsubclasscost_18},
@weaponsubclasscost_19 := {weaponsubclasscost_19},
@weaponsubclasscost_20 := {weaponsubclasscost_20},
@weaponsubclasscost_21 := {weaponsubclasscost_21},
@armorsubclasscost_1 := {armorsubclasscost_1},
@armorsubclasscost_2 := {armorsubclasscost_2},
@armorsubclasscost_3 := {armorsubclasscost_3},
@armorsubclasscost_4 := {armorsubclasscost_4},
@armorsubclasscost_5 := {armorsubclasscost_5},
@armorsubclasscost_6 := {armorsubclasscost_6},
@armorsubclasscost_7 := {armorsubclasscost_7},
@armorsubclasscost_8 := {armorsubclasscost_8};

DELETE FROM durabilitycosts_dbc WHERE
    id=@id
;

INSERT INTO durabilitycosts_dbc (
    id,
    weaponsubclasscost_1,
    weaponsubclasscost_2,
    weaponsubclasscost_3,
    weaponsubclasscost_4,
    weaponsubclasscost_5,
    weaponsubclasscost_6,
    weaponsubclasscost_7,
    weaponsubclasscost_8,
    weaponsubclasscost_9,
    weaponsubclasscost_10,
    weaponsubclasscost_11,
    weaponsubclasscost_12,
    weaponsubclasscost_13,
    weaponsubclasscost_14,
    weaponsubclasscost_15,
    weaponsubclasscost_16,
    weaponsubclasscost_17,
    weaponsubclasscost_18,
    weaponsubclasscost_19,
    weaponsubclasscost_20,
    weaponsubclasscost_21,
    armorsubclasscost_1,
    armorsubclasscost_2,
    armorsubclasscost_3,
    armorsubclasscost_4,
    armorsubclasscost_5,
    armorsubclasscost_6,
    armorsubclasscost_7,
    armorsubclasscost_8
)
VALUES (
    @id,
    @weaponsubclasscost_1,
    @weaponsubclasscost_2,
    @weaponsubclasscost_3,
    @weaponsubclasscost_4,
    @weaponsubclasscost_5,
    @weaponsubclasscost_6,
    @weaponsubclasscost_7,
    @weaponsubclasscost_8,
    @weaponsubclasscost_9,
    @weaponsubclasscost_10,
    @weaponsubclasscost_11,
    @weaponsubclasscost_12,
    @weaponsubclasscost_13,
    @weaponsubclasscost_14,
    @weaponsubclasscost_15,
    @weaponsubclasscost_16,
    @weaponsubclasscost_17,
    @weaponsubclasscost_18,
    @weaponsubclasscost_19,
    @weaponsubclasscost_20,
    @weaponsubclasscost_21,
    @armorsubclasscost_1,
    @armorsubclasscost_2,
    @armorsubclasscost_3,
    @armorsubclasscost_4,
    @armorsubclasscost_5,
    @armorsubclasscost_6,
    @armorsubclasscost_7,
    @armorsubclasscost_8
);

-- END: durabilitycosts_dbc