-- BEGIN: gameobject_template
SET
@entry := {entry},
@type := {type},
@displayid := {displayid},
@name := '{name}',
@iconname := '{iconname}',
@castbarcaption := '{castbarcaption}',
@unk1 := '{unk1}',
@size := {size},
@data0 := {data0},
@data1 := {data1},
@data2 := {data2},
@data3 := {data3},
@data4 := {data4},
@data5 := {data5},
@data6 := {data6},
@data7 := {data7},
@data8 := {data8},
@data9 := {data9},
@data10 := {data10},
@data11 := {data11},
@data12 := {data12},
@data13 := {data13},
@data14 := {data14},
@data15 := {data15},
@data16 := {data16},
@data17 := {data17},
@data18 := {data18},
@data19 := {data19},
@data20 := {data20},
@data21 := {data21},
@data22 := {data22},
@data23 := {data23},
@ainame := '{ainame}',
@scriptname := '{scriptname}',
@verifiedbuild := {verifiedbuild};

DELETE FROM gameobject_template WHERE
    entry=@entry
;

INSERT INTO gameobject_template (
    entry,
    type,
    displayid,
    name,
    iconname,
    castbarcaption,
    unk1,
    size,
    data0,
    data1,
    data2,
    data3,
    data4,
    data5,
    data6,
    data7,
    data8,
    data9,
    data10,
    data11,
    data12,
    data13,
    data14,
    data15,
    data16,
    data17,
    data18,
    data19,
    data20,
    data21,
    data22,
    data23,
    ainame,
    scriptname,
    verifiedbuild
)
VALUES (
    @entry,
    @type,
    @displayid,
    @name,
    @iconname,
    @castbarcaption,
    @unk1,
    @size,
    @data0,
    @data1,
    @data2,
    @data3,
    @data4,
    @data5,
    @data6,
    @data7,
    @data8,
    @data9,
    @data10,
    @data11,
    @data12,
    @data13,
    @data14,
    @data15,
    @data16,
    @data17,
    @data18,
    @data19,
    @data20,
    @data21,
    @data22,
    @data23,
    @ainame,
    @scriptname,
    @verifiedbuild
);

-- END: gameobject_template