
-- START holidays_dbc
SET
@id := {id},
@duration_1 := {duration_1},
@duration_2 := {duration_2},
@duration_3 := {duration_3},
@duration_4 := {duration_4},
@duration_5 := {duration_5},
@duration_6 := {duration_6},
@duration_7 := {duration_7},
@duration_8 := {duration_8},
@duration_9 := {duration_9},
@duration_10 := {duration_10},
@date_1 := {date_1},
@date_2 := {date_2},
@date_3 := {date_3},
@date_4 := {date_4},
@date_5 := {date_5},
@date_6 := {date_6},
@date_7 := {date_7},
@date_8 := {date_8},
@date_9 := {date_9},
@date_10 := {date_10},
@date_11 := {date_11},
@date_12 := {date_12},
@date_13 := {date_13},
@date_14 := {date_14},
@date_15 := {date_15},
@date_16 := {date_16},
@date_17 := {date_17},
@date_18 := {date_18},
@date_19 := {date_19},
@date_20 := {date_20},
@date_21 := {date_21},
@date_22 := {date_22},
@date_23 := {date_23},
@date_24 := {date_24},
@date_25 := {date_25},
@date_26 := {date_26},
@region := {region},
@looping := {looping},
@calendarflags_1 := {calendarflags_1},
@calendarflags_2 := {calendarflags_2},
@calendarflags_3 := {calendarflags_3},
@calendarflags_4 := {calendarflags_4},
@calendarflags_5 := {calendarflags_5},
@calendarflags_6 := {calendarflags_6},
@calendarflags_7 := {calendarflags_7},
@calendarflags_8 := {calendarflags_8},
@calendarflags_9 := {calendarflags_9},
@calendarflags_10 := {calendarflags_10},
@holidaynameid := {holidaynameid},
@holidaydescriptionid := {holidaydescriptionid},
@texturefilename := '{texturefilename}',
@priority := {priority},
@calendarfiltertype := {calendarfiltertype},
@flags := {flags};

DELETE FROM holidays_dbc WHERE
    id=@id
;

INSERT INTO holidays_dbc (
    id,
    duration_1,
    duration_2,
    duration_3,
    duration_4,
    duration_5,
    duration_6,
    duration_7,
    duration_8,
    duration_9,
    duration_10,
    date_1,
    date_2,
    date_3,
    date_4,
    date_5,
    date_6,
    date_7,
    date_8,
    date_9,
    date_10,
    date_11,
    date_12,
    date_13,
    date_14,
    date_15,
    date_16,
    date_17,
    date_18,
    date_19,
    date_20,
    date_21,
    date_22,
    date_23,
    date_24,
    date_25,
    date_26,
    region,
    looping,
    calendarflags_1,
    calendarflags_2,
    calendarflags_3,
    calendarflags_4,
    calendarflags_5,
    calendarflags_6,
    calendarflags_7,
    calendarflags_8,
    calendarflags_9,
    calendarflags_10,
    holidaynameid,
    holidaydescriptionid,
    texturefilename,
    priority,
    calendarfiltertype,
    flags
)
VALUES (
    @id,
    @duration_1,
    @duration_2,
    @duration_3,
    @duration_4,
    @duration_5,
    @duration_6,
    @duration_7,
    @duration_8,
    @duration_9,
    @duration_10,
    @date_1,
    @date_2,
    @date_3,
    @date_4,
    @date_5,
    @date_6,
    @date_7,
    @date_8,
    @date_9,
    @date_10,
    @date_11,
    @date_12,
    @date_13,
    @date_14,
    @date_15,
    @date_16,
    @date_17,
    @date_18,
    @date_19,
    @date_20,
    @date_21,
    @date_22,
    @date_23,
    @date_24,
    @date_25,
    @date_26,
    @region,
    @looping,
    @calendarflags_1,
    @calendarflags_2,
    @calendarflags_3,
    @calendarflags_4,
    @calendarflags_5,
    @calendarflags_6,
    @calendarflags_7,
    @calendarflags_8,
    @calendarflags_9,
    @calendarflags_10,
    @holidaynameid,
    @holidaydescriptionid,
    @texturefilename,
    @priority,
    @calendarfiltertype,
    @flags
);
-- EOF holidays_dbc