
-- START itemset_dbc
SET
@id := {id},
@name_lang_enus := '{name_lang_enus}',
@name_lang_engb := '{name_lang_engb}',
@name_lang_kokr := '{name_lang_kokr}',
@name_lang_frfr := '{name_lang_frfr}',
@name_lang_dede := '{name_lang_dede}',
@name_lang_encn := '{name_lang_encn}',
@name_lang_zhcn := '{name_lang_zhcn}',
@name_lang_entw := '{name_lang_entw}',
@name_lang_zhtw := '{name_lang_zhtw}',
@name_lang_eses := '{name_lang_eses}',
@name_lang_esmx := '{name_lang_esmx}',
@name_lang_ruru := '{name_lang_ruru}',
@name_lang_ptpt := '{name_lang_ptpt}',
@name_lang_ptbr := '{name_lang_ptbr}',
@name_lang_itit := '{name_lang_itit}',
@name_lang_unk := '{name_lang_unk}',
@name_lang_mask := {name_lang_mask},
@itemid_1 := {itemid_1},
@itemid_2 := {itemid_2},
@itemid_3 := {itemid_3},
@itemid_4 := {itemid_4},
@itemid_5 := {itemid_5},
@itemid_6 := {itemid_6},
@itemid_7 := {itemid_7},
@itemid_8 := {itemid_8},
@itemid_9 := {itemid_9},
@itemid_10 := {itemid_10},
@itemid_11 := {itemid_11},
@itemid_12 := {itemid_12},
@itemid_13 := {itemid_13},
@itemid_14 := {itemid_14},
@itemid_15 := {itemid_15},
@itemid_16 := {itemid_16},
@itemid_17 := {itemid_17},
@setspellid_1 := {setspellid_1},
@setspellid_2 := {setspellid_2},
@setspellid_3 := {setspellid_3},
@setspellid_4 := {setspellid_4},
@setspellid_5 := {setspellid_5},
@setspellid_6 := {setspellid_6},
@setspellid_7 := {setspellid_7},
@setspellid_8 := {setspellid_8},
@setthreshold_1 := {setthreshold_1},
@setthreshold_2 := {setthreshold_2},
@setthreshold_3 := {setthreshold_3},
@setthreshold_4 := {setthreshold_4},
@setthreshold_5 := {setthreshold_5},
@setthreshold_6 := {setthreshold_6},
@setthreshold_7 := {setthreshold_7},
@setthreshold_8 := {setthreshold_8},
@requiredskill := {requiredskill},
@requiredskillrank := {requiredskillrank};

DELETE FROM itemset_dbc WHERE
    id=@id
;

INSERT INTO itemset_dbc (
    id,
    name_lang_enus,
    name_lang_engb,
    name_lang_kokr,
    name_lang_frfr,
    name_lang_dede,
    name_lang_encn,
    name_lang_zhcn,
    name_lang_entw,
    name_lang_zhtw,
    name_lang_eses,
    name_lang_esmx,
    name_lang_ruru,
    name_lang_ptpt,
    name_lang_ptbr,
    name_lang_itit,
    name_lang_unk,
    name_lang_mask,
    itemid_1,
    itemid_2,
    itemid_3,
    itemid_4,
    itemid_5,
    itemid_6,
    itemid_7,
    itemid_8,
    itemid_9,
    itemid_10,
    itemid_11,
    itemid_12,
    itemid_13,
    itemid_14,
    itemid_15,
    itemid_16,
    itemid_17,
    setspellid_1,
    setspellid_2,
    setspellid_3,
    setspellid_4,
    setspellid_5,
    setspellid_6,
    setspellid_7,
    setspellid_8,
    setthreshold_1,
    setthreshold_2,
    setthreshold_3,
    setthreshold_4,
    setthreshold_5,
    setthreshold_6,
    setthreshold_7,
    setthreshold_8,
    requiredskill,
    requiredskillrank
)
VALUES (
    @id,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @itemid_1,
    @itemid_2,
    @itemid_3,
    @itemid_4,
    @itemid_5,
    @itemid_6,
    @itemid_7,
    @itemid_8,
    @itemid_9,
    @itemid_10,
    @itemid_11,
    @itemid_12,
    @itemid_13,
    @itemid_14,
    @itemid_15,
    @itemid_16,
    @itemid_17,
    @setspellid_1,
    @setspellid_2,
    @setspellid_3,
    @setspellid_4,
    @setspellid_5,
    @setspellid_6,
    @setspellid_7,
    @setspellid_8,
    @setthreshold_1,
    @setthreshold_2,
    @setthreshold_3,
    @setthreshold_4,
    @setthreshold_5,
    @setthreshold_6,
    @setthreshold_7,
    @setthreshold_8,
    @requiredskill,
    @requiredskillrank
);
-- EOF itemset_dbc