
-- START lfgdungeons_dbc
SET
@id := {id},
@name_lang_enus := '{name_lang_enus}',
@name_lang_engb := '{name_lang_engb}',
@name_lang_kokr := '{name_lang_kokr}',
@name_lang_frfr := '{name_lang_frfr}',
@name_lang_dede := '{name_lang_dede}',
@name_lang_encn := '{name_lang_encn}',
@name_lang_zhcn := '{name_lang_zhcn}',
@name_lang_entw := '{name_lang_entw}',
@name_lang_zhtw := '{name_lang_zhtw}',
@name_lang_eses := '{name_lang_eses}',
@name_lang_esmx := '{name_lang_esmx}',
@name_lang_ruru := '{name_lang_ruru}',
@name_lang_ptpt := '{name_lang_ptpt}',
@name_lang_ptbr := '{name_lang_ptbr}',
@name_lang_itit := '{name_lang_itit}',
@name_lang_unk := '{name_lang_unk}',
@name_lang_mask := {name_lang_mask},
@minlevel := {minlevel},
@maxlevel := {maxlevel},
@target_level := {target_level},
@target_level_min := {target_level_min},
@target_level_max := {target_level_max},
@mapid := {mapid},
@difficulty := {difficulty},
@flags := {flags},
@typeid := {typeid},
@faction := {faction},
@texturefilename := '{texturefilename}',
@expansionlevel := {expansionlevel},
@order_index := {order_index},
@group_id := {group_id},
@description_lang_enus := '{description_lang_enus}',
@description_lang_engb := '{description_lang_engb}',
@description_lang_kokr := '{description_lang_kokr}',
@description_lang_frfr := '{description_lang_frfr}',
@description_lang_dede := '{description_lang_dede}',
@description_lang_encn := '{description_lang_encn}',
@description_lang_zhcn := '{description_lang_zhcn}',
@description_lang_entw := '{description_lang_entw}',
@description_lang_zhtw := '{description_lang_zhtw}',
@description_lang_eses := '{description_lang_eses}',
@description_lang_esmx := '{description_lang_esmx}',
@description_lang_ruru := '{description_lang_ruru}',
@description_lang_ptpt := '{description_lang_ptpt}',
@description_lang_ptbr := '{description_lang_ptbr}',
@description_lang_itit := '{description_lang_itit}',
@description_lang_unk := '{description_lang_unk}',
@description_lang_mask := {description_lang_mask};

DELETE FROM lfgdungeons_dbc WHERE
    id=@id
;

INSERT INTO lfgdungeons_dbc (
    id,
    name_lang_enus,
    name_lang_engb,
    name_lang_kokr,
    name_lang_frfr,
    name_lang_dede,
    name_lang_encn,
    name_lang_zhcn,
    name_lang_entw,
    name_lang_zhtw,
    name_lang_eses,
    name_lang_esmx,
    name_lang_ruru,
    name_lang_ptpt,
    name_lang_ptbr,
    name_lang_itit,
    name_lang_unk,
    name_lang_mask,
    minlevel,
    maxlevel,
    target_level,
    target_level_min,
    target_level_max,
    mapid,
    difficulty,
    flags,
    typeid,
    faction,
    texturefilename,
    expansionlevel,
    order_index,
    group_id,
    description_lang_enus,
    description_lang_engb,
    description_lang_kokr,
    description_lang_frfr,
    description_lang_dede,
    description_lang_encn,
    description_lang_zhcn,
    description_lang_entw,
    description_lang_zhtw,
    description_lang_eses,
    description_lang_esmx,
    description_lang_ruru,
    description_lang_ptpt,
    description_lang_ptbr,
    description_lang_itit,
    description_lang_unk,
    description_lang_mask
)
VALUES (
    @id,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @minlevel,
    @maxlevel,
    @target_level,
    @target_level_min,
    @target_level_max,
    @mapid,
    @difficulty,
    @flags,
    @typeid,
    @faction,
    @texturefilename,
    @expansionlevel,
    @order_index,
    @group_id,
    @description_lang_enus,
    @description_lang_engb,
    @description_lang_kokr,
    @description_lang_frfr,
    @description_lang_dede,
    @description_lang_encn,
    @description_lang_zhcn,
    @description_lang_entw,
    @description_lang_zhtw,
    @description_lang_eses,
    @description_lang_esmx,
    @description_lang_ruru,
    @description_lang_ptpt,
    @description_lang_ptbr,
    @description_lang_itit,
    @description_lang_unk,
    @description_lang_mask
);
-- EOF lfgdungeons_dbc