-- BEGIN: liquidtype_dbc
SET
@id := {id},
@name := '{name}',
@flags := {flags},
@type := {type},
@soundid := {soundid},
@spellid := {spellid},
@maxdarkendepth := {maxdarkendepth},
@fogdarkenintensity := {fogdarkenintensity},
@ambdarkenintensity := {ambdarkenintensity},
@dirdarkenintensity := {dirdarkenintensity},
@lightid := {lightid},
@particlescale := {particlescale},
@particlemovement := {particlemovement},
@particletexslots := {particletexslots},
@materialid := {materialid},
@texture_1 := '{texture_1}',
@texture_2 := '{texture_2}',
@texture_3 := '{texture_3}',
@texture_4 := '{texture_4}',
@texture_5 := '{texture_5}',
@texture_6 := '{texture_6}',
@color_1 := {color_1},
@color_2 := {color_2},
@float_1 := {float_1},
@float_2 := {float_2},
@float_3 := {float_3},
@float_4 := {float_4},
@float_5 := {float_5},
@float_6 := {float_6},
@float_7 := {float_7},
@float_8 := {float_8},
@float_9 := {float_9},
@float_10 := {float_10},
@float_11 := {float_11},
@float_12 := {float_12},
@float_13 := {float_13},
@float_14 := {float_14},
@float_15 := {float_15},
@float_16 := {float_16},
@float_17 := {float_17},
@float_18 := {float_18},
@int_1 := {int_1},
@int_2 := {int_2},
@int_3 := {int_3},
@int_4 := {int_4};

DELETE FROM liquidtype_dbc WHERE
    id=@id
;

INSERT INTO liquidtype_dbc (
    id,
    name,
    flags,
    type,
    soundid,
    spellid,
    maxdarkendepth,
    fogdarkenintensity,
    ambdarkenintensity,
    dirdarkenintensity,
    lightid,
    particlescale,
    particlemovement,
    particletexslots,
    materialid,
    texture_1,
    texture_2,
    texture_3,
    texture_4,
    texture_5,
    texture_6,
    color_1,
    color_2,
    float_1,
    float_2,
    float_3,
    float_4,
    float_5,
    float_6,
    float_7,
    float_8,
    float_9,
    float_10,
    float_11,
    float_12,
    float_13,
    float_14,
    float_15,
    float_16,
    float_17,
    float_18,
    int_1,
    int_2,
    int_3,
    int_4
)
VALUES (
    @id,
    @name,
    @flags,
    @type,
    @soundid,
    @spellid,
    @maxdarkendepth,
    @fogdarkenintensity,
    @ambdarkenintensity,
    @dirdarkenintensity,
    @lightid,
    @particlescale,
    @particlemovement,
    @particletexslots,
    @materialid,
    @texture_1,
    @texture_2,
    @texture_3,
    @texture_4,
    @texture_5,
    @texture_6,
    @color_1,
    @color_2,
    @float_1,
    @float_2,
    @float_3,
    @float_4,
    @float_5,
    @float_6,
    @float_7,
    @float_8,
    @float_9,
    @float_10,
    @float_11,
    @float_12,
    @float_13,
    @float_14,
    @float_15,
    @float_16,
    @float_17,
    @float_18,
    @int_1,
    @int_2,
    @int_3,
    @int_4
);

-- END: liquidtype_dbc