-- BEGIN: map_dbc
SET
@id := {id},
@directory := '{directory}',
@instancetype := {instancetype},
@flags := {flags},
@pvp := {pvp},
@mapname_lang_enus := '{mapname_lang_enus}',
@mapname_lang_engb := '{mapname_lang_engb}',
@mapname_lang_kokr := '{mapname_lang_kokr}',
@mapname_lang_frfr := '{mapname_lang_frfr}',
@mapname_lang_dede := '{mapname_lang_dede}',
@mapname_lang_encn := '{mapname_lang_encn}',
@mapname_lang_zhcn := '{mapname_lang_zhcn}',
@mapname_lang_entw := '{mapname_lang_entw}',
@mapname_lang_zhtw := '{mapname_lang_zhtw}',
@mapname_lang_eses := '{mapname_lang_eses}',
@mapname_lang_esmx := '{mapname_lang_esmx}',
@mapname_lang_ruru := '{mapname_lang_ruru}',
@mapname_lang_ptpt := '{mapname_lang_ptpt}',
@mapname_lang_ptbr := '{mapname_lang_ptbr}',
@mapname_lang_itit := '{mapname_lang_itit}',
@mapname_lang_unk := '{mapname_lang_unk}',
@mapname_lang_mask := {mapname_lang_mask},
@areatableid := {areatableid},
@mapdescription0_lang_enus := '{mapdescription0_lang_enus}',
@mapdescription0_lang_engb := '{mapdescription0_lang_engb}',
@mapdescription0_lang_kokr := '{mapdescription0_lang_kokr}',
@mapdescription0_lang_frfr := '{mapdescription0_lang_frfr}',
@mapdescription0_lang_dede := '{mapdescription0_lang_dede}',
@mapdescription0_lang_encn := '{mapdescription0_lang_encn}',
@mapdescription0_lang_zhcn := '{mapdescription0_lang_zhcn}',
@mapdescription0_lang_entw := '{mapdescription0_lang_entw}',
@mapdescription0_lang_zhtw := '{mapdescription0_lang_zhtw}',
@mapdescription0_lang_eses := '{mapdescription0_lang_eses}',
@mapdescription0_lang_esmx := '{mapdescription0_lang_esmx}',
@mapdescription0_lang_ruru := '{mapdescription0_lang_ruru}',
@mapdescription0_lang_ptpt := '{mapdescription0_lang_ptpt}',
@mapdescription0_lang_ptbr := '{mapdescription0_lang_ptbr}',
@mapdescription0_lang_itit := '{mapdescription0_lang_itit}',
@mapdescription0_lang_unk := '{mapdescription0_lang_unk}',
@mapdescription0_lang_mask := {mapdescription0_lang_mask},
@mapdescription1_lang_enus := '{mapdescription1_lang_enus}',
@mapdescription1_lang_engb := '{mapdescription1_lang_engb}',
@mapdescription1_lang_kokr := '{mapdescription1_lang_kokr}',
@mapdescription1_lang_frfr := '{mapdescription1_lang_frfr}',
@mapdescription1_lang_dede := '{mapdescription1_lang_dede}',
@mapdescription1_lang_encn := '{mapdescription1_lang_encn}',
@mapdescription1_lang_zhcn := '{mapdescription1_lang_zhcn}',
@mapdescription1_lang_entw := '{mapdescription1_lang_entw}',
@mapdescription1_lang_zhtw := '{mapdescription1_lang_zhtw}',
@mapdescription1_lang_eses := '{mapdescription1_lang_eses}',
@mapdescription1_lang_esmx := '{mapdescription1_lang_esmx}',
@mapdescription1_lang_ruru := '{mapdescription1_lang_ruru}',
@mapdescription1_lang_ptpt := '{mapdescription1_lang_ptpt}',
@mapdescription1_lang_ptbr := '{mapdescription1_lang_ptbr}',
@mapdescription1_lang_itit := '{mapdescription1_lang_itit}',
@mapdescription1_lang_unk := '{mapdescription1_lang_unk}',
@mapdescription1_lang_mask := {mapdescription1_lang_mask},
@loadingscreenid := {loadingscreenid},
@minimapiconscale := {minimapiconscale},
@corpsemapid := {corpsemapid},
@corpsex := {corpsex},
@corpsey := {corpsey},
@timeofdayoverride := {timeofdayoverride},
@expansionid := {expansionid},
@raidoffset := {raidoffset},
@maxplayers := {maxplayers};

DELETE FROM map_dbc WHERE
    id=@id
;

INSERT INTO map_dbc (
    id,
    directory,
    instancetype,
    flags,
    pvp,
    mapname_lang_enus,
    mapname_lang_engb,
    mapname_lang_kokr,
    mapname_lang_frfr,
    mapname_lang_dede,
    mapname_lang_encn,
    mapname_lang_zhcn,
    mapname_lang_entw,
    mapname_lang_zhtw,
    mapname_lang_eses,
    mapname_lang_esmx,
    mapname_lang_ruru,
    mapname_lang_ptpt,
    mapname_lang_ptbr,
    mapname_lang_itit,
    mapname_lang_unk,
    mapname_lang_mask,
    areatableid,
    mapdescription0_lang_enus,
    mapdescription0_lang_engb,
    mapdescription0_lang_kokr,
    mapdescription0_lang_frfr,
    mapdescription0_lang_dede,
    mapdescription0_lang_encn,
    mapdescription0_lang_zhcn,
    mapdescription0_lang_entw,
    mapdescription0_lang_zhtw,
    mapdescription0_lang_eses,
    mapdescription0_lang_esmx,
    mapdescription0_lang_ruru,
    mapdescription0_lang_ptpt,
    mapdescription0_lang_ptbr,
    mapdescription0_lang_itit,
    mapdescription0_lang_unk,
    mapdescription0_lang_mask,
    mapdescription1_lang_enus,
    mapdescription1_lang_engb,
    mapdescription1_lang_kokr,
    mapdescription1_lang_frfr,
    mapdescription1_lang_dede,
    mapdescription1_lang_encn,
    mapdescription1_lang_zhcn,
    mapdescription1_lang_entw,
    mapdescription1_lang_zhtw,
    mapdescription1_lang_eses,
    mapdescription1_lang_esmx,
    mapdescription1_lang_ruru,
    mapdescription1_lang_ptpt,
    mapdescription1_lang_ptbr,
    mapdescription1_lang_itit,
    mapdescription1_lang_unk,
    mapdescription1_lang_mask,
    loadingscreenid,
    minimapiconscale,
    corpsemapid,
    corpsex,
    corpsey,
    timeofdayoverride,
    expansionid,
    raidoffset,
    maxplayers
)
VALUES (
    @id,
    @directory,
    @instancetype,
    @flags,
    @pvp,
    @mapname_lang_enus,
    @mapname_lang_engb,
    @mapname_lang_kokr,
    @mapname_lang_frfr,
    @mapname_lang_dede,
    @mapname_lang_encn,
    @mapname_lang_zhcn,
    @mapname_lang_entw,
    @mapname_lang_zhtw,
    @mapname_lang_eses,
    @mapname_lang_esmx,
    @mapname_lang_ruru,
    @mapname_lang_ptpt,
    @mapname_lang_ptbr,
    @mapname_lang_itit,
    @mapname_lang_unk,
    @mapname_lang_mask,
    @areatableid,
    @mapdescription0_lang_enus,
    @mapdescription0_lang_engb,
    @mapdescription0_lang_kokr,
    @mapdescription0_lang_frfr,
    @mapdescription0_lang_dede,
    @mapdescription0_lang_encn,
    @mapdescription0_lang_zhcn,
    @mapdescription0_lang_entw,
    @mapdescription0_lang_zhtw,
    @mapdescription0_lang_eses,
    @mapdescription0_lang_esmx,
    @mapdescription0_lang_ruru,
    @mapdescription0_lang_ptpt,
    @mapdescription0_lang_ptbr,
    @mapdescription0_lang_itit,
    @mapdescription0_lang_unk,
    @mapdescription0_lang_mask,
    @mapdescription1_lang_enus,
    @mapdescription1_lang_engb,
    @mapdescription1_lang_kokr,
    @mapdescription1_lang_frfr,
    @mapdescription1_lang_dede,
    @mapdescription1_lang_encn,
    @mapdescription1_lang_zhcn,
    @mapdescription1_lang_entw,
    @mapdescription1_lang_zhtw,
    @mapdescription1_lang_eses,
    @mapdescription1_lang_esmx,
    @mapdescription1_lang_ruru,
    @mapdescription1_lang_ptpt,
    @mapdescription1_lang_ptbr,
    @mapdescription1_lang_itit,
    @mapdescription1_lang_unk,
    @mapdescription1_lang_mask,
    @loadingscreenid,
    @minimapiconscale,
    @corpsemapid,
    @corpsex,
    @corpsey,
    @timeofdayoverride,
    @expansionid,
    @raidoffset,
    @maxplayers
);

-- END: map_dbc