
-- START spellitemenchantmentcondition_dbc
SET
@id := {id},
@lt_operandtype_1 := {lt_operandtype_1},
@lt_operandtype_2 := {lt_operandtype_2},
@lt_operandtype_3 := {lt_operandtype_3},
@lt_operandtype_4 := {lt_operandtype_4},
@lt_operandtype_5 := {lt_operandtype_5},
@lt_operand_1 := {lt_operand_1},
@lt_operand_2 := {lt_operand_2},
@lt_operand_3 := {lt_operand_3},
@lt_operand_4 := {lt_operand_4},
@lt_operand_5 := {lt_operand_5},
@operator_1 := {operator_1},
@operator_2 := {operator_2},
@operator_3 := {operator_3},
@operator_4 := {operator_4},
@operator_5 := {operator_5},
@rt_operandtype_1 := {rt_operandtype_1},
@rt_operandtype_2 := {rt_operandtype_2},
@rt_operandtype_3 := {rt_operandtype_3},
@rt_operandtype_4 := {rt_operandtype_4},
@rt_operandtype_5 := {rt_operandtype_5},
@rt_operand_1 := {rt_operand_1},
@rt_operand_2 := {rt_operand_2},
@rt_operand_3 := {rt_operand_3},
@rt_operand_4 := {rt_operand_4},
@rt_operand_5 := {rt_operand_5},
@logic_1 := {logic_1},
@logic_2 := {logic_2},
@logic_3 := {logic_3},
@logic_4 := {logic_4},
@logic_5 := {logic_5};

DELETE FROM spellitemenchantmentcondition_dbc WHERE
    id=@id
;

INSERT INTO spellitemenchantmentcondition_dbc (
    id,
    lt_operandtype_1,
    lt_operandtype_2,
    lt_operandtype_3,
    lt_operandtype_4,
    lt_operandtype_5,
    lt_operand_1,
    lt_operand_2,
    lt_operand_3,
    lt_operand_4,
    lt_operand_5,
    operator_1,
    operator_2,
    operator_3,
    operator_4,
    operator_5,
    rt_operandtype_1,
    rt_operandtype_2,
    rt_operandtype_3,
    rt_operandtype_4,
    rt_operandtype_5,
    rt_operand_1,
    rt_operand_2,
    rt_operand_3,
    rt_operand_4,
    rt_operand_5,
    logic_1,
    logic_2,
    logic_3,
    logic_4,
    logic_5
)
VALUES (
    @id,
    @lt_operandtype_1,
    @lt_operandtype_2,
    @lt_operandtype_3,
    @lt_operandtype_4,
    @lt_operandtype_5,
    @lt_operand_1,
    @lt_operand_2,
    @lt_operand_3,
    @lt_operand_4,
    @lt_operand_5,
    @operator_1,
    @operator_2,
    @operator_3,
    @operator_4,
    @operator_5,
    @rt_operandtype_1,
    @rt_operandtype_2,
    @rt_operandtype_3,
    @rt_operandtype_4,
    @rt_operandtype_5,
    @rt_operand_1,
    @rt_operand_2,
    @rt_operand_3,
    @rt_operand_4,
    @rt_operand_5,
    @logic_1,
    @logic_2,
    @logic_3,
    @logic_4,
    @logic_5
);
-- EOF spellitemenchantmentcondition_dbc