
-- START spellvisual_dbc
SET
@id := {id},
@precastkit := {precastkit},
@castkit := {castkit},
@impactkit := {impactkit},
@statekit := {statekit},
@statedonekit := {statedonekit},
@channelkit := {channelkit},
@hasmissile := {hasmissile},
@missilemodel := {missilemodel},
@missilepathtype := {missilepathtype},
@missiledestinationattachment := {missiledestinationattachment},
@missilesound := {missilesound},
@animeventsoundid := {animeventsoundid},
@flags := {flags},
@casterimpactkit := {casterimpactkit},
@targetimpactkit := {targetimpactkit},
@missileattachment := {missileattachment},
@missilefollowgroundheight := {missilefollowgroundheight},
@missilefollowgrounddropspeed := {missilefollowgrounddropspeed},
@missilefollowgroundapproach := {missilefollowgroundapproach},
@missilefollowgroundflags := {missilefollowgroundflags},
@missilemotion := {missilemotion},
@missiletargetingkit := {missiletargetingkit},
@instantareakit := {instantareakit},
@impactareakit := {impactareakit},
@persistentareakit := {persistentareakit},
@missilecastoffsetx := {missilecastoffsetx},
@missilecastoffsety := {missilecastoffsety},
@missilecastoffsetz := {missilecastoffsetz},
@missileimpactoffsetx := {missileimpactoffsetx},
@missileimpactoffsety := {missileimpactoffsety},
@missileimpactoffsetz := {missileimpactoffsetz};

DELETE FROM spellvisual_dbc WHERE
    id=@id
;

INSERT INTO spellvisual_dbc (
    id,
    precastkit,
    castkit,
    impactkit,
    statekit,
    statedonekit,
    channelkit,
    hasmissile,
    missilemodel,
    missilepathtype,
    missiledestinationattachment,
    missilesound,
    animeventsoundid,
    flags,
    casterimpactkit,
    targetimpactkit,
    missileattachment,
    missilefollowgroundheight,
    missilefollowgrounddropspeed,
    missilefollowgroundapproach,
    missilefollowgroundflags,
    missilemotion,
    missiletargetingkit,
    instantareakit,
    impactareakit,
    persistentareakit,
    missilecastoffsetx,
    missilecastoffsety,
    missilecastoffsetz,
    missileimpactoffsetx,
    missileimpactoffsety,
    missileimpactoffsetz
)
VALUES (
    @id,
    @precastkit,
    @castkit,
    @impactkit,
    @statekit,
    @statedonekit,
    @channelkit,
    @hasmissile,
    @missilemodel,
    @missilepathtype,
    @missiledestinationattachment,
    @missilesound,
    @animeventsoundid,
    @flags,
    @casterimpactkit,
    @targetimpactkit,
    @missileattachment,
    @missilefollowgroundheight,
    @missilefollowgrounddropspeed,
    @missilefollowgroundapproach,
    @missilefollowgroundflags,
    @missilemotion,
    @missiletargetingkit,
    @instantareakit,
    @impactareakit,
    @persistentareakit,
    @missilecastoffsetx,
    @missilecastoffsety,
    @missilecastoffsetz,
    @missileimpactoffsetx,
    @missileimpactoffsety,
    @missileimpactoffsetz
);
-- EOF spellvisual_dbc