
-- START spell_dbc
SET
@id := {id},
@category := {category},
@dispeltype := {dispeltype},
@mechanic := {mechanic},
@attributes := {attributes},
@attributesex := {attributesex},
@attributesex2 := {attributesex2},
@attributesex3 := {attributesex3},
@attributesex4 := {attributesex4},
@attributesex5 := {attributesex5},
@attributesex6 := {attributesex6},
@attributesex7 := {attributesex7},
@shapeshiftmask := {shapeshiftmask},
@unk_320_2 := {unk_320_2},
@shapeshiftexclude := {shapeshiftexclude},
@unk_320_3 := {unk_320_3},
@targets := {targets},
@targetcreaturetype := {targetcreaturetype},
@requiresspellfocus := {requiresspellfocus},
@facingcasterflags := {facingcasterflags},
@casteraurastate := {casteraurastate},
@targetaurastate := {targetaurastate},
@excludecasteraurastate := {excludecasteraurastate},
@excludetargetaurastate := {excludetargetaurastate},
@casterauraspell := {casterauraspell},
@targetauraspell := {targetauraspell},
@excludecasterauraspell := {excludecasterauraspell},
@excludetargetauraspell := {excludetargetauraspell},
@castingtimeindex := {castingtimeindex},
@recoverytime := {recoverytime},
@categoryrecoverytime := {categoryrecoverytime},
@interruptflags := {interruptflags},
@aurainterruptflags := {aurainterruptflags},
@channelinterruptflags := {channelinterruptflags},
@proctypemask := {proctypemask},
@procchance := {procchance},
@proccharges := {proccharges},
@maxlevel := {maxlevel},
@baselevel := {baselevel},
@spelllevel := {spelllevel},
@durationindex := {durationindex},
@powertype := {powertype},
@manacost := {manacost},
@manacostperlevel := {manacostperlevel},
@manapersecond := {manapersecond},
@manapersecondperlevel := {manapersecondperlevel},
@rangeindex := {rangeindex},
@speed := {speed},
@modalnextspell := {modalnextspell},
@cumulativeaura := {cumulativeaura},
@totem_1 := {totem_1},
@totem_2 := {totem_2},
@reagent_1 := {reagent_1},
@reagent_2 := {reagent_2},
@reagent_3 := {reagent_3},
@reagent_4 := {reagent_4},
@reagent_5 := {reagent_5},
@reagent_6 := {reagent_6},
@reagent_7 := {reagent_7},
@reagent_8 := {reagent_8},
@reagentcount_1 := {reagentcount_1},
@reagentcount_2 := {reagentcount_2},
@reagentcount_3 := {reagentcount_3},
@reagentcount_4 := {reagentcount_4},
@reagentcount_5 := {reagentcount_5},
@reagentcount_6 := {reagentcount_6},
@reagentcount_7 := {reagentcount_7},
@reagentcount_8 := {reagentcount_8},
@equippeditemclass := {equippeditemclass},
@equippeditemsubclass := {equippeditemsubclass},
@equippediteminvtypes := {equippediteminvtypes},
@effect_1 := {effect_1},
@effect_2 := {effect_2},
@effect_3 := {effect_3},
@effectdiesides_1 := {effectdiesides_1},
@effectdiesides_2 := {effectdiesides_2},
@effectdiesides_3 := {effectdiesides_3},
@effectrealpointsperlevel_1 := {effectrealpointsperlevel_1},
@effectrealpointsperlevel_2 := {effectrealpointsperlevel_2},
@effectrealpointsperlevel_3 := {effectrealpointsperlevel_3},
@effectbasepoints_1 := {effectbasepoints_1},
@effectbasepoints_2 := {effectbasepoints_2},
@effectbasepoints_3 := {effectbasepoints_3},
@effectmechanic_1 := {effectmechanic_1},
@effectmechanic_2 := {effectmechanic_2},
@effectmechanic_3 := {effectmechanic_3},
@implicittargeta_1 := {implicittargeta_1},
@implicittargeta_2 := {implicittargeta_2},
@implicittargeta_3 := {implicittargeta_3},
@implicittargetb_1 := {implicittargetb_1},
@implicittargetb_2 := {implicittargetb_2},
@implicittargetb_3 := {implicittargetb_3},
@effectradiusindex_1 := {effectradiusindex_1},
@effectradiusindex_2 := {effectradiusindex_2},
@effectradiusindex_3 := {effectradiusindex_3},
@effectaura_1 := {effectaura_1},
@effectaura_2 := {effectaura_2},
@effectaura_3 := {effectaura_3},
@effectauraperiod_1 := {effectauraperiod_1},
@effectauraperiod_2 := {effectauraperiod_2},
@effectauraperiod_3 := {effectauraperiod_3},
@effectmultiplevalue_1 := {effectmultiplevalue_1},
@effectmultiplevalue_2 := {effectmultiplevalue_2},
@effectmultiplevalue_3 := {effectmultiplevalue_3},
@effectchaintargets_1 := {effectchaintargets_1},
@effectchaintargets_2 := {effectchaintargets_2},
@effectchaintargets_3 := {effectchaintargets_3},
@effectitemtype_1 := {effectitemtype_1},
@effectitemtype_2 := {effectitemtype_2},
@effectitemtype_3 := {effectitemtype_3},
@effectmiscvalue_1 := {effectmiscvalue_1},
@effectmiscvalue_2 := {effectmiscvalue_2},
@effectmiscvalue_3 := {effectmiscvalue_3},
@effectmiscvalueb_1 := {effectmiscvalueb_1},
@effectmiscvalueb_2 := {effectmiscvalueb_2},
@effectmiscvalueb_3 := {effectmiscvalueb_3},
@effecttriggerspell_1 := {effecttriggerspell_1},
@effecttriggerspell_2 := {effecttriggerspell_2},
@effecttriggerspell_3 := {effecttriggerspell_3},
@effectpointspercombo_1 := {effectpointspercombo_1},
@effectpointspercombo_2 := {effectpointspercombo_2},
@effectpointspercombo_3 := {effectpointspercombo_3},
@effectspellclassmaska_1 := {effectspellclassmaska_1},
@effectspellclassmaska_2 := {effectspellclassmaska_2},
@effectspellclassmaska_3 := {effectspellclassmaska_3},
@effectspellclassmaskb_1 := {effectspellclassmaskb_1},
@effectspellclassmaskb_2 := {effectspellclassmaskb_2},
@effectspellclassmaskb_3 := {effectspellclassmaskb_3},
@effectspellclassmaskc_1 := {effectspellclassmaskc_1},
@effectspellclassmaskc_2 := {effectspellclassmaskc_2},
@effectspellclassmaskc_3 := {effectspellclassmaskc_3},
@spellvisualid_1 := {spellvisualid_1},
@spellvisualid_2 := {spellvisualid_2},
@spelliconid := {spelliconid},
@activeiconid := {activeiconid},
@spellpriority := {spellpriority},
@name_lang_enus := '{name_lang_enus}',
@name_lang_engb := '{name_lang_engb}',
@name_lang_kokr := '{name_lang_kokr}',
@name_lang_frfr := '{name_lang_frfr}',
@name_lang_dede := '{name_lang_dede}',
@name_lang_encn := '{name_lang_encn}',
@name_lang_zhcn := '{name_lang_zhcn}',
@name_lang_entw := '{name_lang_entw}',
@name_lang_zhtw := '{name_lang_zhtw}',
@name_lang_eses := '{name_lang_eses}',
@name_lang_esmx := '{name_lang_esmx}',
@name_lang_ruru := '{name_lang_ruru}',
@name_lang_ptpt := '{name_lang_ptpt}',
@name_lang_ptbr := '{name_lang_ptbr}',
@name_lang_itit := '{name_lang_itit}',
@name_lang_unk := '{name_lang_unk}',
@name_lang_mask := {name_lang_mask},
@namesubtext_lang_enus := '{namesubtext_lang_enus}',
@namesubtext_lang_engb := '{namesubtext_lang_engb}',
@namesubtext_lang_kokr := '{namesubtext_lang_kokr}',
@namesubtext_lang_frfr := '{namesubtext_lang_frfr}',
@namesubtext_lang_dede := '{namesubtext_lang_dede}',
@namesubtext_lang_encn := '{namesubtext_lang_encn}',
@namesubtext_lang_zhcn := '{namesubtext_lang_zhcn}',
@namesubtext_lang_entw := '{namesubtext_lang_entw}',
@namesubtext_lang_zhtw := '{namesubtext_lang_zhtw}',
@namesubtext_lang_eses := '{namesubtext_lang_eses}',
@namesubtext_lang_esmx := '{namesubtext_lang_esmx}',
@namesubtext_lang_ruru := '{namesubtext_lang_ruru}',
@namesubtext_lang_ptpt := '{namesubtext_lang_ptpt}',
@namesubtext_lang_ptbr := '{namesubtext_lang_ptbr}',
@namesubtext_lang_itit := '{namesubtext_lang_itit}',
@namesubtext_lang_unk := '{namesubtext_lang_unk}',
@namesubtext_lang_mask := {namesubtext_lang_mask},
@description_lang_enus := '{description_lang_enus}',
@description_lang_engb := '{description_lang_engb}',
@description_lang_kokr := '{description_lang_kokr}',
@description_lang_frfr := '{description_lang_frfr}',
@description_lang_dede := '{description_lang_dede}',
@description_lang_encn := '{description_lang_encn}',
@description_lang_zhcn := '{description_lang_zhcn}',
@description_lang_entw := '{description_lang_entw}',
@description_lang_zhtw := '{description_lang_zhtw}',
@description_lang_eses := '{description_lang_eses}',
@description_lang_esmx := '{description_lang_esmx}',
@description_lang_ruru := '{description_lang_ruru}',
@description_lang_ptpt := '{description_lang_ptpt}',
@description_lang_ptbr := '{description_lang_ptbr}',
@description_lang_itit := '{description_lang_itit}',
@description_lang_unk := '{description_lang_unk}',
@description_lang_mask := {description_lang_mask},
@auradescription_lang_enus := '{auradescription_lang_enus}',
@auradescription_lang_engb := '{auradescription_lang_engb}',
@auradescription_lang_kokr := '{auradescription_lang_kokr}',
@auradescription_lang_frfr := '{auradescription_lang_frfr}',
@auradescription_lang_dede := '{auradescription_lang_dede}',
@auradescription_lang_encn := '{auradescription_lang_encn}',
@auradescription_lang_zhcn := '{auradescription_lang_zhcn}',
@auradescription_lang_entw := '{auradescription_lang_entw}',
@auradescription_lang_zhtw := '{auradescription_lang_zhtw}',
@auradescription_lang_eses := '{auradescription_lang_eses}',
@auradescription_lang_esmx := '{auradescription_lang_esmx}',
@auradescription_lang_ruru := '{auradescription_lang_ruru}',
@auradescription_lang_ptpt := '{auradescription_lang_ptpt}',
@auradescription_lang_ptbr := '{auradescription_lang_ptbr}',
@auradescription_lang_itit := '{auradescription_lang_itit}',
@auradescription_lang_unk := '{auradescription_lang_unk}',
@auradescription_lang_mask := {auradescription_lang_mask},
@manacostpct := {manacostpct},
@startrecoverycategory := {startrecoverycategory},
@startrecoverytime := {startrecoverytime},
@maxtargetlevel := {maxtargetlevel},
@spellclassset := {spellclassset},
@spellclassmask_1 := {spellclassmask_1},
@spellclassmask_2 := {spellclassmask_2},
@spellclassmask_3 := {spellclassmask_3},
@maxtargets := {maxtargets},
@defensetype := {defensetype},
@preventiontype := {preventiontype},
@stancebarorder := {stancebarorder},
@effectchainamplitude_1 := {effectchainamplitude_1},
@effectchainamplitude_2 := {effectchainamplitude_2},
@effectchainamplitude_3 := {effectchainamplitude_3},
@minfactionid := {minfactionid},
@minreputation := {minreputation},
@requiredauravision := {requiredauravision},
@requiredtotemcategoryid_1 := {requiredtotemcategoryid_1},
@requiredtotemcategoryid_2 := {requiredtotemcategoryid_2},
@requiredareasid := {requiredareasid},
@schoolmask := {schoolmask},
@runecostid := {runecostid},
@spellmissileid := {spellmissileid},
@powerdisplayid := {powerdisplayid},
@effectbonusmultiplier_1 := {effectbonusmultiplier_1},
@effectbonusmultiplier_2 := {effectbonusmultiplier_2},
@effectbonusmultiplier_3 := {effectbonusmultiplier_3},
@spelldescriptionvariableid := {spelldescriptionvariableid},
@spelldifficultyid := {spelldifficultyid};

DELETE FROM spell_dbc WHERE
    id=@id
;

INSERT INTO spell_dbc (
    id,
    category,
    dispeltype,
    mechanic,
    attributes,
    attributesex,
    attributesex2,
    attributesex3,
    attributesex4,
    attributesex5,
    attributesex6,
    attributesex7,
    shapeshiftmask,
    unk_320_2,
    shapeshiftexclude,
    unk_320_3,
    targets,
    targetcreaturetype,
    requiresspellfocus,
    facingcasterflags,
    casteraurastate,
    targetaurastate,
    excludecasteraurastate,
    excludetargetaurastate,
    casterauraspell,
    targetauraspell,
    excludecasterauraspell,
    excludetargetauraspell,
    castingtimeindex,
    recoverytime,
    categoryrecoverytime,
    interruptflags,
    aurainterruptflags,
    channelinterruptflags,
    proctypemask,
    procchance,
    proccharges,
    maxlevel,
    baselevel,
    spelllevel,
    durationindex,
    powertype,
    manacost,
    manacostperlevel,
    manapersecond,
    manapersecondperlevel,
    rangeindex,
    speed,
    modalnextspell,
    cumulativeaura,
    totem_1,
    totem_2,
    reagent_1,
    reagent_2,
    reagent_3,
    reagent_4,
    reagent_5,
    reagent_6,
    reagent_7,
    reagent_8,
    reagentcount_1,
    reagentcount_2,
    reagentcount_3,
    reagentcount_4,
    reagentcount_5,
    reagentcount_6,
    reagentcount_7,
    reagentcount_8,
    equippeditemclass,
    equippeditemsubclass,
    equippediteminvtypes,
    effect_1,
    effect_2,
    effect_3,
    effectdiesides_1,
    effectdiesides_2,
    effectdiesides_3,
    effectrealpointsperlevel_1,
    effectrealpointsperlevel_2,
    effectrealpointsperlevel_3,
    effectbasepoints_1,
    effectbasepoints_2,
    effectbasepoints_3,
    effectmechanic_1,
    effectmechanic_2,
    effectmechanic_3,
    implicittargeta_1,
    implicittargeta_2,
    implicittargeta_3,
    implicittargetb_1,
    implicittargetb_2,
    implicittargetb_3,
    effectradiusindex_1,
    effectradiusindex_2,
    effectradiusindex_3,
    effectaura_1,
    effectaura_2,
    effectaura_3,
    effectauraperiod_1,
    effectauraperiod_2,
    effectauraperiod_3,
    effectmultiplevalue_1,
    effectmultiplevalue_2,
    effectmultiplevalue_3,
    effectchaintargets_1,
    effectchaintargets_2,
    effectchaintargets_3,
    effectitemtype_1,
    effectitemtype_2,
    effectitemtype_3,
    effectmiscvalue_1,
    effectmiscvalue_2,
    effectmiscvalue_3,
    effectmiscvalueb_1,
    effectmiscvalueb_2,
    effectmiscvalueb_3,
    effecttriggerspell_1,
    effecttriggerspell_2,
    effecttriggerspell_3,
    effectpointspercombo_1,
    effectpointspercombo_2,
    effectpointspercombo_3,
    effectspellclassmaska_1,
    effectspellclassmaska_2,
    effectspellclassmaska_3,
    effectspellclassmaskb_1,
    effectspellclassmaskb_2,
    effectspellclassmaskb_3,
    effectspellclassmaskc_1,
    effectspellclassmaskc_2,
    effectspellclassmaskc_3,
    spellvisualid_1,
    spellvisualid_2,
    spelliconid,
    activeiconid,
    spellpriority,
    name_lang_enus,
    name_lang_engb,
    name_lang_kokr,
    name_lang_frfr,
    name_lang_dede,
    name_lang_encn,
    name_lang_zhcn,
    name_lang_entw,
    name_lang_zhtw,
    name_lang_eses,
    name_lang_esmx,
    name_lang_ruru,
    name_lang_ptpt,
    name_lang_ptbr,
    name_lang_itit,
    name_lang_unk,
    name_lang_mask,
    namesubtext_lang_enus,
    namesubtext_lang_engb,
    namesubtext_lang_kokr,
    namesubtext_lang_frfr,
    namesubtext_lang_dede,
    namesubtext_lang_encn,
    namesubtext_lang_zhcn,
    namesubtext_lang_entw,
    namesubtext_lang_zhtw,
    namesubtext_lang_eses,
    namesubtext_lang_esmx,
    namesubtext_lang_ruru,
    namesubtext_lang_ptpt,
    namesubtext_lang_ptbr,
    namesubtext_lang_itit,
    namesubtext_lang_unk,
    namesubtext_lang_mask,
    description_lang_enus,
    description_lang_engb,
    description_lang_kokr,
    description_lang_frfr,
    description_lang_dede,
    description_lang_encn,
    description_lang_zhcn,
    description_lang_entw,
    description_lang_zhtw,
    description_lang_eses,
    description_lang_esmx,
    description_lang_ruru,
    description_lang_ptpt,
    description_lang_ptbr,
    description_lang_itit,
    description_lang_unk,
    description_lang_mask,
    auradescription_lang_enus,
    auradescription_lang_engb,
    auradescription_lang_kokr,
    auradescription_lang_frfr,
    auradescription_lang_dede,
    auradescription_lang_encn,
    auradescription_lang_zhcn,
    auradescription_lang_entw,
    auradescription_lang_zhtw,
    auradescription_lang_eses,
    auradescription_lang_esmx,
    auradescription_lang_ruru,
    auradescription_lang_ptpt,
    auradescription_lang_ptbr,
    auradescription_lang_itit,
    auradescription_lang_unk,
    auradescription_lang_mask,
    manacostpct,
    startrecoverycategory,
    startrecoverytime,
    maxtargetlevel,
    spellclassset,
    spellclassmask_1,
    spellclassmask_2,
    spellclassmask_3,
    maxtargets,
    defensetype,
    preventiontype,
    stancebarorder,
    effectchainamplitude_1,
    effectchainamplitude_2,
    effectchainamplitude_3,
    minfactionid,
    minreputation,
    requiredauravision,
    requiredtotemcategoryid_1,
    requiredtotemcategoryid_2,
    requiredareasid,
    schoolmask,
    runecostid,
    spellmissileid,
    powerdisplayid,
    effectbonusmultiplier_1,
    effectbonusmultiplier_2,
    effectbonusmultiplier_3,
    spelldescriptionvariableid,
    spelldifficultyid
)
VALUES (
    @id,
    @category,
    @dispeltype,
    @mechanic,
    @attributes,
    @attributesex,
    @attributesex2,
    @attributesex3,
    @attributesex4,
    @attributesex5,
    @attributesex6,
    @attributesex7,
    @shapeshiftmask,
    @unk_320_2,
    @shapeshiftexclude,
    @unk_320_3,
    @targets,
    @targetcreaturetype,
    @requiresspellfocus,
    @facingcasterflags,
    @casteraurastate,
    @targetaurastate,
    @excludecasteraurastate,
    @excludetargetaurastate,
    @casterauraspell,
    @targetauraspell,
    @excludecasterauraspell,
    @excludetargetauraspell,
    @castingtimeindex,
    @recoverytime,
    @categoryrecoverytime,
    @interruptflags,
    @aurainterruptflags,
    @channelinterruptflags,
    @proctypemask,
    @procchance,
    @proccharges,
    @maxlevel,
    @baselevel,
    @spelllevel,
    @durationindex,
    @powertype,
    @manacost,
    @manacostperlevel,
    @manapersecond,
    @manapersecondperlevel,
    @rangeindex,
    @speed,
    @modalnextspell,
    @cumulativeaura,
    @totem_1,
    @totem_2,
    @reagent_1,
    @reagent_2,
    @reagent_3,
    @reagent_4,
    @reagent_5,
    @reagent_6,
    @reagent_7,
    @reagent_8,
    @reagentcount_1,
    @reagentcount_2,
    @reagentcount_3,
    @reagentcount_4,
    @reagentcount_5,
    @reagentcount_6,
    @reagentcount_7,
    @reagentcount_8,
    @equippeditemclass,
    @equippeditemsubclass,
    @equippediteminvtypes,
    @effect_1,
    @effect_2,
    @effect_3,
    @effectdiesides_1,
    @effectdiesides_2,
    @effectdiesides_3,
    @effectrealpointsperlevel_1,
    @effectrealpointsperlevel_2,
    @effectrealpointsperlevel_3,
    @effectbasepoints_1,
    @effectbasepoints_2,
    @effectbasepoints_3,
    @effectmechanic_1,
    @effectmechanic_2,
    @effectmechanic_3,
    @implicittargeta_1,
    @implicittargeta_2,
    @implicittargeta_3,
    @implicittargetb_1,
    @implicittargetb_2,
    @implicittargetb_3,
    @effectradiusindex_1,
    @effectradiusindex_2,
    @effectradiusindex_3,
    @effectaura_1,
    @effectaura_2,
    @effectaura_3,
    @effectauraperiod_1,
    @effectauraperiod_2,
    @effectauraperiod_3,
    @effectmultiplevalue_1,
    @effectmultiplevalue_2,
    @effectmultiplevalue_3,
    @effectchaintargets_1,
    @effectchaintargets_2,
    @effectchaintargets_3,
    @effectitemtype_1,
    @effectitemtype_2,
    @effectitemtype_3,
    @effectmiscvalue_1,
    @effectmiscvalue_2,
    @effectmiscvalue_3,
    @effectmiscvalueb_1,
    @effectmiscvalueb_2,
    @effectmiscvalueb_3,
    @effecttriggerspell_1,
    @effecttriggerspell_2,
    @effecttriggerspell_3,
    @effectpointspercombo_1,
    @effectpointspercombo_2,
    @effectpointspercombo_3,
    @effectspellclassmaska_1,
    @effectspellclassmaska_2,
    @effectspellclassmaska_3,
    @effectspellclassmaskb_1,
    @effectspellclassmaskb_2,
    @effectspellclassmaskb_3,
    @effectspellclassmaskc_1,
    @effectspellclassmaskc_2,
    @effectspellclassmaskc_3,
    @spellvisualid_1,
    @spellvisualid_2,
    @spelliconid,
    @activeiconid,
    @spellpriority,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @namesubtext_lang_enus,
    @namesubtext_lang_engb,
    @namesubtext_lang_kokr,
    @namesubtext_lang_frfr,
    @namesubtext_lang_dede,
    @namesubtext_lang_encn,
    @namesubtext_lang_zhcn,
    @namesubtext_lang_entw,
    @namesubtext_lang_zhtw,
    @namesubtext_lang_eses,
    @namesubtext_lang_esmx,
    @namesubtext_lang_ruru,
    @namesubtext_lang_ptpt,
    @namesubtext_lang_ptbr,
    @namesubtext_lang_itit,
    @namesubtext_lang_unk,
    @namesubtext_lang_mask,
    @description_lang_enus,
    @description_lang_engb,
    @description_lang_kokr,
    @description_lang_frfr,
    @description_lang_dede,
    @description_lang_encn,
    @description_lang_zhcn,
    @description_lang_entw,
    @description_lang_zhtw,
    @description_lang_eses,
    @description_lang_esmx,
    @description_lang_ruru,
    @description_lang_ptpt,
    @description_lang_ptbr,
    @description_lang_itit,
    @description_lang_unk,
    @description_lang_mask,
    @auradescription_lang_enus,
    @auradescription_lang_engb,
    @auradescription_lang_kokr,
    @auradescription_lang_frfr,
    @auradescription_lang_dede,
    @auradescription_lang_encn,
    @auradescription_lang_zhcn,
    @auradescription_lang_entw,
    @auradescription_lang_zhtw,
    @auradescription_lang_eses,
    @auradescription_lang_esmx,
    @auradescription_lang_ruru,
    @auradescription_lang_ptpt,
    @auradescription_lang_ptbr,
    @auradescription_lang_itit,
    @auradescription_lang_unk,
    @auradescription_lang_mask,
    @manacostpct,
    @startrecoverycategory,
    @startrecoverytime,
    @maxtargetlevel,
    @spellclassset,
    @spellclassmask_1,
    @spellclassmask_2,
    @spellclassmask_3,
    @maxtargets,
    @defensetype,
    @preventiontype,
    @stancebarorder,
    @effectchainamplitude_1,
    @effectchainamplitude_2,
    @effectchainamplitude_3,
    @minfactionid,
    @minreputation,
    @requiredauravision,
    @requiredtotemcategoryid_1,
    @requiredtotemcategoryid_2,
    @requiredareasid,
    @schoolmask,
    @runecostid,
    @spellmissileid,
    @powerdisplayid,
    @effectbonusmultiplier_1,
    @effectbonusmultiplier_2,
    @effectbonusmultiplier_3,
    @spelldescriptionvariableid,
    @spelldifficultyid
);
-- EOF spell_dbc