
-- START spellrange_dbc
SET
@id := {id},
@rangemin_1 := {rangemin_1},
@rangemin_2 := {rangemin_2},
@rangemax_1 := {rangemax_1},
@rangemax_2 := {rangemax_2},
@flags := {flags},
@displayname_lang_enus := '{displayname_lang_enus}',
@displayname_lang_engb := '{displayname_lang_engb}',
@displayname_lang_kokr := '{displayname_lang_kokr}',
@displayname_lang_frfr := '{displayname_lang_frfr}',
@displayname_lang_dede := '{displayname_lang_dede}',
@displayname_lang_encn := '{displayname_lang_encn}',
@displayname_lang_zhcn := '{displayname_lang_zhcn}',
@displayname_lang_entw := '{displayname_lang_entw}',
@displayname_lang_zhtw := '{displayname_lang_zhtw}',
@displayname_lang_eses := '{displayname_lang_eses}',
@displayname_lang_esmx := '{displayname_lang_esmx}',
@displayname_lang_ruru := '{displayname_lang_ruru}',
@displayname_lang_ptpt := '{displayname_lang_ptpt}',
@displayname_lang_ptbr := '{displayname_lang_ptbr}',
@displayname_lang_itit := '{displayname_lang_itit}',
@displayname_lang_unk := '{displayname_lang_unk}',
@displayname_lang_mask := {displayname_lang_mask},
@displaynameshort_lang_enus := '{displaynameshort_lang_enus}',
@displaynameshort_lang_engb := '{displaynameshort_lang_engb}',
@displaynameshort_lang_kokr := '{displaynameshort_lang_kokr}',
@displaynameshort_lang_frfr := '{displaynameshort_lang_frfr}',
@displaynameshort_lang_dede := '{displaynameshort_lang_dede}',
@displaynameshort_lang_encn := '{displaynameshort_lang_encn}',
@displaynameshort_lang_zhcn := '{displaynameshort_lang_zhcn}',
@displaynameshort_lang_entw := '{displaynameshort_lang_entw}',
@displaynameshort_lang_zhtw := '{displaynameshort_lang_zhtw}',
@displaynameshort_lang_eses := '{displaynameshort_lang_eses}',
@displaynameshort_lang_esmx := '{displaynameshort_lang_esmx}',
@displaynameshort_lang_ruru := '{displaynameshort_lang_ruru}',
@displaynameshort_lang_ptpt := '{displaynameshort_lang_ptpt}',
@displaynameshort_lang_ptbr := '{displaynameshort_lang_ptbr}',
@displaynameshort_lang_itit := '{displaynameshort_lang_itit}',
@displaynameshort_lang_unk := '{displaynameshort_lang_unk}',
@displaynameshort_lang_mask := {displaynameshort_lang_mask};

DELETE FROM spellrange_dbc WHERE
    id=@id
;

INSERT INTO spellrange_dbc (
    id,
    rangemin_1,
    rangemin_2,
    rangemax_1,
    rangemax_2,
    flags,
    displayname_lang_enus,
    displayname_lang_engb,
    displayname_lang_kokr,
    displayname_lang_frfr,
    displayname_lang_dede,
    displayname_lang_encn,
    displayname_lang_zhcn,
    displayname_lang_entw,
    displayname_lang_zhtw,
    displayname_lang_eses,
    displayname_lang_esmx,
    displayname_lang_ruru,
    displayname_lang_ptpt,
    displayname_lang_ptbr,
    displayname_lang_itit,
    displayname_lang_unk,
    displayname_lang_mask,
    displaynameshort_lang_enus,
    displaynameshort_lang_engb,
    displaynameshort_lang_kokr,
    displaynameshort_lang_frfr,
    displaynameshort_lang_dede,
    displaynameshort_lang_encn,
    displaynameshort_lang_zhcn,
    displaynameshort_lang_entw,
    displaynameshort_lang_zhtw,
    displaynameshort_lang_eses,
    displaynameshort_lang_esmx,
    displaynameshort_lang_ruru,
    displaynameshort_lang_ptpt,
    displaynameshort_lang_ptbr,
    displaynameshort_lang_itit,
    displaynameshort_lang_unk,
    displaynameshort_lang_mask
)
VALUES (
    @id,
    @rangemin_1,
    @rangemin_2,
    @rangemax_1,
    @rangemax_2,
    @flags,
    @displayname_lang_enus,
    @displayname_lang_engb,
    @displayname_lang_kokr,
    @displayname_lang_frfr,
    @displayname_lang_dede,
    @displayname_lang_encn,
    @displayname_lang_zhcn,
    @displayname_lang_entw,
    @displayname_lang_zhtw,
    @displayname_lang_eses,
    @displayname_lang_esmx,
    @displayname_lang_ruru,
    @displayname_lang_ptpt,
    @displayname_lang_ptbr,
    @displayname_lang_itit,
    @displayname_lang_unk,
    @displayname_lang_mask,
    @displaynameshort_lang_enus,
    @displaynameshort_lang_engb,
    @displaynameshort_lang_kokr,
    @displaynameshort_lang_frfr,
    @displaynameshort_lang_dede,
    @displaynameshort_lang_encn,
    @displaynameshort_lang_zhcn,
    @displaynameshort_lang_entw,
    @displaynameshort_lang_zhtw,
    @displaynameshort_lang_eses,
    @displaynameshort_lang_esmx,
    @displaynameshort_lang_ruru,
    @displaynameshort_lang_ptpt,
    @displaynameshort_lang_ptbr,
    @displaynameshort_lang_itit,
    @displaynameshort_lang_unk,
    @displaynameshort_lang_mask
);
-- EOF spellrange_dbc