
-- START spellshapeshiftform_dbc
SET
@id := {id},
@bonusactionbar := {bonusactionbar},
@name_lang_enus := '{name_lang_enus}',
@name_lang_engb := '{name_lang_engb}',
@name_lang_kokr := '{name_lang_kokr}',
@name_lang_frfr := '{name_lang_frfr}',
@name_lang_dede := '{name_lang_dede}',
@name_lang_encn := '{name_lang_encn}',
@name_lang_zhcn := '{name_lang_zhcn}',
@name_lang_entw := '{name_lang_entw}',
@name_lang_zhtw := '{name_lang_zhtw}',
@name_lang_eses := '{name_lang_eses}',
@name_lang_esmx := '{name_lang_esmx}',
@name_lang_ruru := '{name_lang_ruru}',
@name_lang_ptpt := '{name_lang_ptpt}',
@name_lang_ptbr := '{name_lang_ptbr}',
@name_lang_itit := '{name_lang_itit}',
@name_lang_unk := '{name_lang_unk}',
@name_lang_mask := {name_lang_mask},
@flags := {flags},
@creaturetype := {creaturetype},
@attackiconid := {attackiconid},
@combatroundtime := {combatroundtime},
@creaturedisplayid_1 := {creaturedisplayid_1},
@creaturedisplayid_2 := {creaturedisplayid_2},
@creaturedisplayid_3 := {creaturedisplayid_3},
@creaturedisplayid_4 := {creaturedisplayid_4},
@presetspellid_1 := {presetspellid_1},
@presetspellid_2 := {presetspellid_2},
@presetspellid_3 := {presetspellid_3},
@presetspellid_4 := {presetspellid_4},
@presetspellid_5 := {presetspellid_5},
@presetspellid_6 := {presetspellid_6},
@presetspellid_7 := {presetspellid_7},
@presetspellid_8 := {presetspellid_8};

DELETE FROM spellshapeshiftform_dbc WHERE
    id=@id
;

INSERT INTO spellshapeshiftform_dbc (
    id,
    bonusactionbar,
    name_lang_enus,
    name_lang_engb,
    name_lang_kokr,
    name_lang_frfr,
    name_lang_dede,
    name_lang_encn,
    name_lang_zhcn,
    name_lang_entw,
    name_lang_zhtw,
    name_lang_eses,
    name_lang_esmx,
    name_lang_ruru,
    name_lang_ptpt,
    name_lang_ptbr,
    name_lang_itit,
    name_lang_unk,
    name_lang_mask,
    flags,
    creaturetype,
    attackiconid,
    combatroundtime,
    creaturedisplayid_1,
    creaturedisplayid_2,
    creaturedisplayid_3,
    creaturedisplayid_4,
    presetspellid_1,
    presetspellid_2,
    presetspellid_3,
    presetspellid_4,
    presetspellid_5,
    presetspellid_6,
    presetspellid_7,
    presetspellid_8
)
VALUES (
    @id,
    @bonusactionbar,
    @name_lang_enus,
    @name_lang_engb,
    @name_lang_kokr,
    @name_lang_frfr,
    @name_lang_dede,
    @name_lang_encn,
    @name_lang_zhcn,
    @name_lang_entw,
    @name_lang_zhtw,
    @name_lang_eses,
    @name_lang_esmx,
    @name_lang_ruru,
    @name_lang_ptpt,
    @name_lang_ptbr,
    @name_lang_itit,
    @name_lang_unk,
    @name_lang_mask,
    @flags,
    @creaturetype,
    @attackiconid,
    @combatroundtime,
    @creaturedisplayid_1,
    @creaturedisplayid_2,
    @creaturedisplayid_3,
    @creaturedisplayid_4,
    @presetspellid_1,
    @presetspellid_2,
    @presetspellid_3,
    @presetspellid_4,
    @presetspellid_5,
    @presetspellid_6,
    @presetspellid_7,
    @presetspellid_8
);
-- EOF spellshapeshiftform_dbc