def sql_new_achievement_criteria_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            achievement_id = data['achievement_id'],
            type = data['type'],
            asset_id = data['asset_id'],
            quantity = data['quantity'],
            start_event = data['start_event'],
            start_asset = data['start_asset'],
            fail_event = data['fail_event'],
            fail_asset = data['fail_asset'],
            description_lang_enus = data['description_lang_enus'],
            description_lang_engb = data['description_lang_engb'],
            description_lang_kokr = data['description_lang_kokr'],
            description_lang_frfr = data['description_lang_frfr'],
            description_lang_dede = data['description_lang_dede'],
            description_lang_encn = data['description_lang_encn'],
            description_lang_zhcn = data['description_lang_zhcn'],
            description_lang_entw = data['description_lang_entw'],
            description_lang_zhtw = data['description_lang_zhtw'],
            description_lang_eses = data['description_lang_eses'],
            description_lang_esmx = data['description_lang_esmx'],
            description_lang_ruru = data['description_lang_ruru'],
            description_lang_ptpt = data['description_lang_ptpt'],
            description_lang_ptbr = data['description_lang_ptbr'],
            description_lang_itit = data['description_lang_itit'],
            description_lang_unk = data['description_lang_unk'],
            description_lang_mask = data['description_lang_mask'],
            flags = data['flags'],
            timer_start_event = data['timer_start_event'],
            timer_asset_id = data['timer_asset_id'],
            timer_time = data['timer_time'],
            ui_order = data['ui_order'],
        )