def sql_new_creature(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            guid = data['guid'],
            id1 = data['id1'],
            id2 = data['id2'],
            id3 = data['id3'],
            map = data['map'],
            zoneid = data['zoneid'],
            areaid = data['areaid'],
            spawnmask = data['spawnmask'],
            phasemask = data['phasemask'],
            equipment_id = data['equipment_id'],
            position_x = data['position_x'],
            position_y = data['position_y'],
            position_z = data['position_z'],
            orientation = data['orientation'],
            spawntimesecs = data['spawntimesecs'],
            wander_distance = data['wander_distance'],
            currentwaypoint = data['currentwaypoint'],
            curhealth = data['curhealth'],
            curmana = data['curmana'],
            movementtype = data['movementtype'],
            npcflag = data['npcflag'],
            unit_flags = data['unit_flags'],
            dynamicflags = data['dynamicflags'],
            scriptname = data['scriptname'],
            verifiedbuild = data['verifiedbuild'],
            createobject = data['createobject'],
            comment = data['comment'],
        )