def sql_new_gameobject(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            guid = data['guid'],
            id = data['id'],
            map = data['map'],
            zoneid = data['zoneid'],
            areaid = data['areaid'],
            spawnmask = data['spawnmask'],
            phasemask = data['phasemask'],
            position_x = data['position_x'],
            position_y = data['position_y'],
            position_z = data['position_z'],
            orientation = data['orientation'],
            rotation0 = data['rotation0'],
            rotation1 = data['rotation1'],
            rotation2 = data['rotation2'],
            rotation3 = data['rotation3'],
            spawntimesecs = data['spawntimesecs'],
            animprogress = data['animprogress'],
            state = data['state'],
            scriptname = data['scriptname'],
            verifiedbuild = data['verifiedbuild'],
            comment = data['comment'],
        )