def sql_new_itemdisplayinfo_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            modelname_1 = data['modelname_1'],
            modelname_2 = data['modelname_2'],
            modeltexture_1 = data['modeltexture_1'],
            modeltexture_2 = data['modeltexture_2'],
            inventoryicon_1 = data['inventoryicon_1'],
            inventoryicon_2 = data['inventoryicon_2'],
            geosetgroup_1 = data['geosetgroup_1'],
            geosetgroup_2 = data['geosetgroup_2'],
            geosetgroup_3 = data['geosetgroup_3'],
            flags = data['flags'],
            spellvisualid = data['spellvisualid'],
            groupsoundindex = data['groupsoundindex'],
            helmetgeosetvis_1 = data['helmetgeosetvis_1'],
            helmetgeosetvis_2 = data['helmetgeosetvis_2'],
            texture_1 = data['texture_1'],
            texture_2 = data['texture_2'],
            texture_3 = data['texture_3'],
            texture_4 = data['texture_4'],
            texture_5 = data['texture_5'],
            texture_6 = data['texture_6'],
            texture_7 = data['texture_7'],
            texture_8 = data['texture_8'],
            itemvisual = data['itemvisual'],
            particlecolorid = data['particlecolorid'],
        )