def sql_new_lock_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            type_1 = data['type_1'],
            type_2 = data['type_2'],
            type_3 = data['type_3'],
            type_4 = data['type_4'],
            type_5 = data['type_5'],
            type_6 = data['type_6'],
            type_7 = data['type_7'],
            type_8 = data['type_8'],
            index_1 = data['index_1'],
            index_2 = data['index_2'],
            index_3 = data['index_3'],
            index_4 = data['index_4'],
            index_5 = data['index_5'],
            index_6 = data['index_6'],
            index_7 = data['index_7'],
            index_8 = data['index_8'],
            skill_1 = data['skill_1'],
            skill_2 = data['skill_2'],
            skill_3 = data['skill_3'],
            skill_4 = data['skill_4'],
            skill_5 = data['skill_5'],
            skill_6 = data['skill_6'],
            skill_7 = data['skill_7'],
            skill_8 = data['skill_8'],
            action_1 = data['action_1'],
            action_2 = data['action_2'],
            action_3 = data['action_3'],
            action_4 = data['action_4'],
            action_5 = data['action_5'],
            action_6 = data['action_6'],
            action_7 = data['action_7'],
            action_8 = data['action_8'],
        )