def sql_new_smart_scripts(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            entryorguid = data['entryorguid'],
            source_type = data['source_type'],
            id = data['id'],
            link = data['link'],
            event_type = data['event_type'],
            event_phase_mask = data['event_phase_mask'],
            event_chance = data['event_chance'],
            event_flags = data['event_flags'],
            event_param1 = data['event_param1'],
            event_param2 = data['event_param2'],
            event_param3 = data['event_param3'],
            event_param4 = data['event_param4'],
            event_param5 = data['event_param5'],
            event_param6 = data['event_param6'],
            action_type = data['action_type'],
            action_param1 = data['action_param1'],
            action_param2 = data['action_param2'],
            action_param3 = data['action_param3'],
            action_param4 = data['action_param4'],
            action_param5 = data['action_param5'],
            action_param6 = data['action_param6'],
            target_type = data['target_type'],
            target_param1 = data['target_param1'],
            target_param2 = data['target_param2'],
            target_param3 = data['target_param3'],
            target_param4 = data['target_param4'],
            target_x = data['target_x'],
            target_y = data['target_y'],
            target_z = data['target_z'],
            target_o = data['target_o'],
            comment = data['comment'],
        )