def sql_new_spellitemenchantmentcondition_dbc(data, path):
    with open(path, 'r') as fd:
        return fd.read().format(
            id = data['id'],
            lt_operandtype_1 = data['lt_operandtype_1'],
            lt_operandtype_2 = data['lt_operandtype_2'],
            lt_operandtype_3 = data['lt_operandtype_3'],
            lt_operandtype_4 = data['lt_operandtype_4'],
            lt_operandtype_5 = data['lt_operandtype_5'],
            lt_operand_1 = data['lt_operand_1'],
            lt_operand_2 = data['lt_operand_2'],
            lt_operand_3 = data['lt_operand_3'],
            lt_operand_4 = data['lt_operand_4'],
            lt_operand_5 = data['lt_operand_5'],
            operator_1 = data['operator_1'],
            operator_2 = data['operator_2'],
            operator_3 = data['operator_3'],
            operator_4 = data['operator_4'],
            operator_5 = data['operator_5'],
            rt_operandtype_1 = data['rt_operandtype_1'],
            rt_operandtype_2 = data['rt_operandtype_2'],
            rt_operandtype_3 = data['rt_operandtype_3'],
            rt_operandtype_4 = data['rt_operandtype_4'],
            rt_operandtype_5 = data['rt_operandtype_5'],
            rt_operand_1 = data['rt_operand_1'],
            rt_operand_2 = data['rt_operand_2'],
            rt_operand_3 = data['rt_operand_3'],
            rt_operand_4 = data['rt_operand_4'],
            rt_operand_5 = data['rt_operand_5'],
            logic_1 = data['logic_1'],
            logic_2 = data['logic_2'],
            logic_3 = data['logic_3'],
            logic_4 = data['logic_4'],
            logic_5 = data['logic_5'],
        )